In [2]:
%run "/content/drive/MyDrive/Scan_code_notebook/colab_keepalive.ipynb"

✅ Keep-alive active — Colab won't disconnect during scan
Speed test: 1.9s for 5 tickers
Per ticker: 0.39s

    500 tickers → estimated 3 min
   1000 tickers → estimated 6 min
   2000 tickers → estimated 13 min
   6700 tickers → estimated 43 min

TIP: Use S&P 500 + Nifty 500 only (~1000 tickers) for scans < 15 min
     Skip Russell 2000 unless you specifically need small caps
✅ fast_fetch_all() ready
   Fetches 500 tickers in ~3 min instead of 30 min

# Daily Scanner + Stockbee

**Run:** Pre-market or after market close

**Scans:** Bearish Momentum · VCP · Satish · Hardik · NR6 · Rocket Base · EP Breakout · 20d/2m High · Gap Up · Up 4%+ · Stockbee (5 scans)

**Universes:** S&P 500 · Russell 2000 · Nifty 500 (toggle with `INCLUDE_NIFTY`)

**Publishes to:** GitHub `public/data` + Supabase

**Runtime > Run all**

In [3]:
# CELL 1 — Install
import subprocess, sys
subprocess.check_call([sys.executable,"-m","pip","install","-q",
    "yfinance","tqdm","requests","lxml","supabase","openpyxl"])
print("Ready")

Ready

In [4]:
# CELL 2 — Settings
import warnings; warnings.filterwarnings("ignore")
import requests, io, time, gc
import pandas as pd
import numpy as np
import yfinance as yf
from datetime import datetime

# ── Universe / market mode ──────────────────────────────────
# Set SCAN_MARKET env var to 'india' or 'usa' for scheduled automation.
# INDIA: scan Nifty 500 only.
# USA  : scan S&P 500 + Russell 2000 only.
# Default: 'both' (scans everything, same as before)
import os
SCAN_MARKET = os.environ.get("SCAN_MARKET", "both").strip().lower()
if SCAN_MARKET not in {"india", "usa", "both"}:
    raise ValueError(f"SCAN_MARKET must be 'india', 'usa', or 'both', got: {SCAN_MARKET!r}")

if SCAN_MARKET == "india":
    INCLUDE_NIFTY   = True
    INCLUDE_SP500   = False
    INCLUDE_RUSSELL = False
elif SCAN_MARKET == "usa":
    INCLUDE_NIFTY   = False
    INCLUDE_SP500   = True
    INCLUDE_RUSSELL = False   # set True if you want Russell too
else:  # both
    INCLUDE_NIFTY   = True
    INCLUDE_SP500   = True
    INCLUDE_RUSSELL = False   # keep off by default — slow

print(f"SCAN_MARKET : {SCAN_MARKET.upper()}")
print(f"  S&P 500   : {INCLUDE_SP500}")
print(f"  Russell   : {INCLUDE_RUSSELL}")
print(f"  Nifty 500 : {INCLUDE_NIFTY}")
# (overridden above by SCAN_MARKET)
# INCLUDE_NIFTY         = True    # False = skip Nifty 500
BATCH_SIZE            = 40
SLEEP_BETWEEN_BATCHES = 3
SHEET_ID = "1rzc_6fZoHMFi1Ee75zRmIuGxeCWog1E62pZp9c1Lsfs"
print(f"Nifty included: {INCLUDE_NIFTY}")
print(f"Sheet: https://docs.google.com/spreadsheets/d/{SHEET_ID}")

SCAN_MARKET : BOTH
  S&P 500   : True
  Russell   : False
  Nifty 500 : True
Nifty included: True
Sheet: https://docs.google.com/spreadsheets/d/1rzc_6fZoHMFi1Ee75zRmIuGxeCWog1E62pZp9c1Lsfs

In [5]:
# CELL 3 — Load tickers
HEADERS = {"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36"}

def get_sp500():
    try:
        html = requests.get("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",headers=HEADERS,timeout=15).text
        t = [str(x).replace(".","-") for x in pd.read_html(io.StringIO(html))[0]["Symbol"].tolist()]
        print(f"  S&P 500      : {len(t)}"); return t
    except Exception as e:
        print(f"  SP500 failed: {e}"); return []

def get_russell2000():
    try:
        nyse = requests.get("https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nyse/nyse_tickers.txt",headers=HEADERS,timeout=15).text.strip().split()
        nasd = requests.get("https://raw.githubusercontent.com/rreichel3/US-Stock-Symbols/main/nasdaq/nasdaq_tickers.txt",headers=HEADERS,timeout=15).text.strip().split()
        sp_csv = requests.get("https://raw.githubusercontent.com/datasets/s-and-p-500-companies/main/data/constituents.csv",headers=HEADERS,timeout=15).text
        sp_set = set(pd.read_csv(io.StringIO(sp_csv))["Symbol"].str.replace(".","-",regex=False).tolist())
        all_t = list(dict.fromkeys(nyse+nasd))
        t = [x for x in all_t if x.isalpha() and 2<=len(x)<=4 and x not in sp_set][:2000]
        print(f"  Russell 2000 : {len(t)}"); return t
    except Exception as e:
        print(f"  R2K failed: {e}"); return []

def get_nifty500():
    symbols = [
        "360ONE","3MINDIA","ABB","ACC","ACMESOLAR","AIAENG","APLAPOLLO","AUBANK",
        "AWL","AADHARHFC","AARTIIND","AAVAS","ABBOTINDIA","ACE","ACUTAAS","ADANIENSOL",
        "ADANIENT","ADANIGREEN","ADANIPORTS","ADANIPOWER","ATGL","ABCAPITAL","ABFRL","ABLBL",
        "ABREL","ABSLAMC","CPPLUS","AEGISLOG","AEGISVOPAK","AFCONS","AFFLE","AJANTPHARM",
        "ALKEM","ABDL","AMBER","AMBUJACEM","ANANDRATHI","ANANTRAJ","ANGELONE","ANTHEM",
        "ANURAS","APARINDS","APOLLOHOSP","APOLLOTYRE","APTUS","ASAHIINDIA","ASHOKLEY","ASIANPAINT",
        "ASTERDM","ASTRAL","ATHERENERG","ATUL","AUROPHARMA","AIIL","DMART","AXISBANK",
        "BEML","BLS","BSE","BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BAJAJHLDNG","BAJAJHFL",
        "BALKRISIND","BALRAMCHIN","BANDHANBNK","BANKBARODA","BANKINDIA","MAHABANK","BATAINDIA","BAYERCROP",
        "BELRISE","BERGEPAINT","BDL","BEL","BHARATFORG","BHEL","BPCL","BHARTIARTL",
        "BHARTIHEXA","BIKAJI","GROWW","BIOCON","BSOFT","BLUEDART","BLUEJET","BLUESTARCO",
        "BBTC","BOSCHLTD","FIRSTCRY","BRIGADE","BRITANNIA","MAPMYINDIA","CCL","CESC",
        "CGPOWER","CIEINDIA","CRISIL","CANFINHOME","CANBK","CANHLIFE","CAPLIPOINT","CGCL",
        "CARBORUNIV","CARTRADE","CASTROLIND","CEATLTD","CEMPRO","CENTRALBK","CDSL","CHALET",
        "CHAMBLFERT","CHENNPETRO","CHOICEIN","CHOLAHLDNG","CHOLAFIN","CIPLA","CUB","CLEAN",
        "COALINDIA","COCHINSHIP","COFORGE","COHANCE","COLPAL","CAMS","CONCORDBIO","CONCOR",
        "COROMANDEL","CRAFTSMAN","CREDITACC","CROMPTON","CUMMINSIND","CYIENT","DCMSHRIRAM","DLF",
        "DOMS","DABUR","DALBHARAT","DATAPATTNS","DEEPAKFERT","DEEPAKNTR","DELHIVERY","DEVYANI",
        "DIVISLAB","DIXON","LALPATHLAB","DRREDDY","EIDPARRY","EIHOTEL","EICHERMOT","ELECON",
        "ELGIEQUIP","EMAMILTD","EMCURE","EMMVEE","ENDURANCE","ENGINERSIN","ERIS","ESCORTS",
        "ETERNAL","EXIDEIND","NYKAA","FEDERALBNK","FACT","FINCABLES","FSL","FIVESTAR",
        "FORCEMOT","FORTIS","GAIL","GMRAIRPORT","GABRIEL","GALLANTT","GRSE","GICRE",
        "GILLETTE","GLAND","GLAXO","GLENMARK","MEDANTA","GODIGIT","GPIL","GODFRYPHLP",
        "GODREJCP","GODREJIND","GODREJPROP","GRANULES","GRAPHITE","GRASIM","GRAVITA","GESHIP",
        "FLUOROCHEM","GMDCLTD","HEG","HBLENGINE","HCLTECH","HDBFS","HDFCAMC","HDFCBANK",
        "HDFCLIFE","HFCL","HAVELLS","HEROMOTOCO","HEXT","HSCL","HINDALCO","HAL",
        "HINDCOPPER","HINDPETRO","HINDUNILVR","HINDZINC","POWERINDIA","HOMEFIRST","HONASA","HONAUT",
        "HUDCO","HYUNDAI","ICICIBANK","ICICIGI","ICICIAMC","ICICIPRULI","IDBI","IDFCFIRSTB",
        "IFCI","IIFL","IRB","IRCON","ITCHOTELS","ITC","ITI","INDGN",
        "INDIACEM","INDIAMART","INDIANB","IEX","INDHOTEL","IOC","IOB","IRCTC",
        "IRFC","IREDA","IGL","INDUSTOWER","INDUSINDBK","NAUKRI","INFY","INOXWIND",
        "INTELLECT","INDIGO","IGIL","IKS","IPCALAB","JBCHEPHARM","JKCEMENT","JBMA",
        "JKTYRE","JMFINANCIL","JSWCEMENT","JSWDULUX","JSWENERGY","JSWINFRA","JSWSTEEL","JAINREC",
        "JPPOWER","JINDALSAW","JSL","JINDALSTEL","JIOFIN","JUBLFOOD","JUBLINGREA","JUBLPHARMA",
        "JWL","JYOTICNC","KPRMILL","KEI","KPITTECH","KAJARIACER","KPIL","KALYANKJIL",
        "KARURVYSYA","KAYNES","KEC","KFINTECH","KIRLOSENG","KOTAKBANK","KIMS","LTF",
        "LTTS","LGEINDIA","LICHSGFIN","LTFOODS","LTM","LT","LATENTVIEW","LAURUSLABS",
        "THELEELA","LEMONTREE","LENSKART","LICI","LINDEINDIA","LLOYDSME","LODHA","LUPIN",
        "MMTC","MRF","MGL","M&MFIN","M&M","MANAPPURAM","MRPL","MANKIND",
        "MARICO","MARUTI","MFSL","MAXHEALTH","MAZDOCK","MEESHO","MINDACORP","MSUMI",
        "MOTILALOFS","MPHASIS","MCX","MUTHOOTFIN","NATCOPHARM","NBCC","NCC","NHPC",
        "NLCINDIA","NMDC","NSLNISP","NTPCGREEN","NTPC","NH","NATIONALUM","NAVA",
        "NAVINFLUOR","NESTLEIND","NETWEB","NEULANDLAB","NEWGEN","NAM-INDIA","NIVABUPA","NUVAMA",
        "NUVOCO","OBEROIRLTY","ONGC","OIL","OLAELEC","OLECTRA","PAYTM","ONESOURCE",
        "OFSS","POLICYBZR","PCBL","PGEL","PIIND","PNBHOUSING","PTCIL","PVRINOX",
        "PAGEIND","PARADEEP","PATANJALI","PERSISTENT","PETRONET","PFIZER","PHOENIXLTD","PWL",
        "PIDILITIND","PINELABS","PIRAMALFIN","PPLPHARMA","POLYMED","POLYCAB","POONAWALLA","PFC",
        "POWERGRID","PREMIERENE","PRESTIGE","PNB","RRKABEL","RBLBANK","RECLTD","RHIM",
        "RITES","RADICO","RVNL","RAILTEL","RAINBOW","RKFORGE","REDINGTON","RELIANCE",
        "RPOWER","SBFC","SBICARD","SBILIFE","SJVN","SRF","SAGILITY","SAILIFE",
        "SAMMAANCAP","MOTHERSON","SAPPHIRE","SARDAEN","SAREGAMA","SCHAEFFLER","SCHNEIDER","SCI",
        "SHREECEM","SHRIRAMFIN","SHYAMMETL","ENRIN","SIEMENS","SIGNATURE","SOBHA","SOLARINDS",
        "SONACOMS","SONATSOFTW","STARHEALTH","SBIN","SAIL","SUMICHEM","SUNPHARMA","SUNTV",
        "SUNDARMFIN","SUPREMEIND","SPLPETRO","SUZLON","SWANCORP","SWIGGY","SYNGENE","SYRMA",
        "TBOTEK","TVSMOTOR","TATACAP","TATACHEM","TATACOMM","TCS","TATACONSUM","TATAELXSI",
        "TATAINVEST","TMCV","TMPV","TATAPOWER","TATASTEEL","TATATECH","TTML","TECHM",
        "TECHNOE","TEGA","TEJASNET","TENNIND","NIACL","RAMCOCEM","THERMAX","TIMKEN",
        "TITAGARH","TITAN","TORNTPHARM","TORNTPOWER","TARIL","TRAVELFOOD","TRENT","TRIDENT",
        "TRITURBINE","TIINDIA","UCOBANK","UNOMINDA","UPL","UTIAMC","ULTRACEMCO","UNIONBANK",
        "UBL","UNITDSPR","URBANCO","USHAMART","VTL","VBL","VEDL","VIJAYA","542772","523395","526881","544176","524348","524208","543748","541988","500002","500488","500410","532268","544283","532762","543349","539254","512599","541450","532921","533096","542066","519183","540691","535755","544403","500040","543374","544466","540205","540025","500003","544407","544634","543534","544280","542752","500187","532811","532683","532331","544356","544222","506235","533573","543322","539523","506767","544203","521070","500008","540902","500425","543415","515055","543235","544449","532259","523694","544111","533758","508869","540879","500877","543335","543657","542919","542484","500101","515030","523716","500477","533271","500820","544022","526433","540975","532493","532830","506820","544397","544527","500027","540611","532668","524804","539177","505010","543896","512573","540376","539807","544181","543458","532215","532395","544061","532977","533229","500031","500034","532978","500032","500490","544252","544042","530999","502355","523319","500038","531112","500039","541153","532134","532149","532525","544209","500042","500043","506285","544405","500048","509480","500052","503960","541143","500049","500493","500103","500547","532454","544162","543653","544603","532523","500335","532400","500463","544288","540073","526612","544009","500067","544484","500020","543212","502219","523398","500530","544226","532929","500825","543425","532834","543523","511196","532483","544583","544580","533267","540710","544614","524742","531595","513375","534804","543333","524091","500870","519600","500878","544223","544012","509496","532885","532548","532443","500084","500093","542399","500085","543336","500110","531358","504973","511243","532756","500087","532210","543318","543441","533278","540678","532541","543064","500830",
        "543232","543960","531344","506395","544644","543276","541770","500092","544439","539876","542867","500480","530843","543933","532175","533151","500096","542216","543428","532528","532772","523367","543650","500645","506401","543529","543330","507717","522163","540047","540701","543812","532488","540699","532868","543306","544045","544350","539524","500124","505242","500125","532927","532922","505200","523127","500840","500123","505700","543626","500128","522074","544421","531162","532832","544210","544608","543983","543533","540153","532178","544122","544290","544095","543332","500135","543243","540596","500133","500495","543320","543532","543482","531508","500086","531599","544027","500469","505744","532768","526227","541557","533333","500144","500940","532809","524743","543663","544030","500033","532843","500150","543384","544613","543652","543317","505714","532155","540935","532726","526367","514167","542011","500655","509557","543489","522275","540755","532285","500171","507815","543245","500660","532296","543654","533104","505255","532754","543490","544179","543401","532734","500163","540743","532424","500164","533150","532630","539725","526729","530655","500168","544140","532482","509488","500300","505710","533282","500620","501455","538979","542857","526797","506076","544801","509079","530001","524226","539336","542812","517300","532181","500670","533248","500690","538567","541019","543227","544057","543600","533162","531531","517354","508486","517271","532281","544429","541729","500180","540777","539787","509631","500292","543242","519552","500182","544362","500183","524735","500184","500440","532859","541154","500185","513599","519126","500186","500104","500696","500188","542905","543187","522215","543259","544014","522064","517174","540530","544274","532174","540716","544658","540133","532835","500116","543932","539437","505726","500106","542773","532636","539056","544172","530005","500201","543311","544044","532189","542726","532814","540750","533047","530965","532388","542830","543257","544026","543258","521016","532612","541336","532514","532150","534816","532187","532777","500209","500210","544067","543667","544046","544836","539083","532851","538835","539448","544311","544309","524164","500214","524494","532947","541956","533033","544325","500875","523610","532644","532940","532976","512237","500219","544537","532627","532209","520051","544118","522285","532605","500227","500378","532508","532286","531543","543940","500380","532162","530007","523405","544480","500710","533148","532642","543994","500228","520057","534600","533155","543271","530019","544129","543980","533272","535648","532926","544081","532889","500233","544423","522287","543278","500235","532468","500165","532652","532899","543664","532054","532714","517569","505890","532732","543669","543720","524019","540680","532967","500241","500245","500243","533293","505283","521248","543273","532942","532924","500247","523323","542323","542651","530813","543308","544263","543328","500249","533519","540115","500250","526947","543714","500510","543398","540222","543277","544192","544408","541233","544600","544576","500253","543526","523457","539992","512463","512455","500252","543287","532783","540005","532796","517206","500257","539957","500108","500266","500265","532720","500520","533088","532313","540768","533169","531213","500109","543904","541974","531642","524404","532500","540749","523704","544008","500271","543220","522249","543237","544088","543427","544632","543426","542650","544587","538962","541195","513377","533286","533080","500288","543498","532892","526299","532440","500290","543253","542597","543270","500460","534091","533398","544055","524709","539551","524816","532234","523630","544467","513023","532504","508989","543280","534309","500294","542665","544647","505355","500790","543945","532798","524558","540900","533098","543952","523385","540767","500307","532698","544286","513683","526371","543768","500730","500672","530367","544289","532555","531209","543988","543334","533273","500312","533106","544225","532439","543396","544292","530135","532466","524372","535754","541301","500314","544595","544418","544256","523642","532827","532900","543530","539889","543367","544645","500368","531120","543390","534809","506590","538730","532808","533179","532522","500680","533581","544609","530305","500331","539883","544606","544597","543635","513519","500333","540173","539150","532486","531768","542652","524051","524000","532810","532898","539302","522205","506022","540724","523539","544238","533274","540293","532748","542907","500338","530117","500126","500459","543527","540544","532524","539006","533295","532461","532689","544367","539978","543981","532735","532497","542649","543265","500339","543524","517522","500355","532369","532527","533262","524230","543417","520111","534597","533122","544240","500330","540065","532955","532805","543957","532884","530517","500325","532939","532915","535322","505509","543248","534076","541556","543325","543213","543228","532983","542333","544578","539450","543387","544526","523025","502090","544282","544306","543989","543984","535789","517334","541163","504918","514234","530073","544250","500674","543358","543397","504614","532163","532663","524667","543959","543066","540719","505790","534139","526807","543936","544533","539199","512329","501423","531431","540797","522034","538666","535602","540725","540203","531201","530549","523598","513097","532638","500387","532670","544490","511218","543299","544390","500550","543990","532029","543686","540673","503811","533206","544572","500472","538562","541967","544447","505192","532784","532725","541540","543300","532221","532218","500285","544344","503806","544469","540575","543412","500112","500113","513262","542760","532374","532531","526951","506222","517168","506655","544619","542920","532872","524715","532733","544066","500403","500215","500404","512179","532509","509930","500405","543434","500336","530239","532667","503310","500407","544285","517385","539268","543573","533553","532390","543596","506854","532790","543249","519091","544574","500770","500483","532540","500800","500408","501301","544569","500570","500400","500470","544028","532371","543321","544174","540212","539658","532755","542141","532804","543413","540595","544612","533326","533158","542460","501425","500850","540769","503100","500260","500411","500412","500413","539871","507205","532856","500414","522113","532375","532966","500114","500420","532779","532928","532349","544317","544443","500251","521064","532356","544824","533655","517506","540762","520056","532343","509243","543965","532505","500148","511742","542904","532538","506690","544322","532477","543689","532478","532432","532539","512070","544515","517146","543238","543942","532953","534976","507880","531266","532867","533269","519156","532156","534392","502986","541578","540180","543463","523261","544321","543528","520113","543350","544488","524200","544307","516072","512529","532822","532757","500575","539118","509966","544277","534618","544642","517498","532144","532553","514162","500444","505533","544570","500238","507685","532300","538268","505872","543950","543992","532648","543985","505537","533339","504067","533023","532321","531335"
    ]
    t = [f"BOM.{s}" if str(s)[0].isdigit() else f"{s}.NS" for s in dict.fromkeys(symbols)]
    print(f"  Nifty 500    : {len(t)}"); return t

print("Loading tickers...")
sp500      = get_sp500()
r2000      = get_russell2000()
r2000_only = [t for t in r2000 if t not in set(sp500)]
nifty500   = get_nifty500() if INCLUDE_NIFTY else []
print(f"  Total        : {len(sp500)+len(r2000_only)+len(nifty500)}")

Loading tickers...
  S&P 500      : 503
  Russell 2000 : 2000
  Nifty 500    : 1483
  Total        : 3986

In [6]:
# CELL 4 — Indicators
import pandas as pd
import numpy as np

def sma(s,n): return s.rolling(n).mean()
def ema(s,n): return s.ewm(span=n,adjust=False).mean()
def rsi(s,n=14):
    d=s.diff()
    g=d.clip(lower=0).rolling(n).mean()
    l=(-d.clip(upper=0)).rolling(n).mean()
    return 100-(100/(1+g/l.replace(0,np.nan)))
def _f(x):
    try: return float(x)
    except: return float("nan")
def _range(d,i):
    try: return _f(d["High"].iloc[-(i+1)]) - _f(d["Low"].iloc[-(i+1)])
    except: return float("nan")
def vwap_intraday(h):
    h=h.copy()
    h["_d"]=h.index.normalize()
    h["_tp"]=(h["High"]+h["Low"]+h["Close"])/3
    tpv=h.groupby("_d").apply(lambda g:(g["_tp"]*g["Volume"]).cumsum()).values
    cvol=h.groupby("_d")["Volume"].cumsum().values
    return pd.Series(tpv/cvol,index=h.index)
print("Indicators ready")

Indicators ready

In [7]:
# CELL 5 — Fetchers (daily/weekly + intraday separated)
import yfinance as yf
import pandas as pd
import time

def fetch_batch(tickers, period, interval, retries=2):
    """Daily / weekly batch fetcher."""
    out = {}
    if not tickers: return out
    for attempt in range(retries+1):
        try:
            raw = yf.download(tickers, period=period, interval=interval,
                              group_by="ticker", auto_adjust=False,
                              progress=False, threads=True)
            if raw.empty: break
            if len(tickers)==1:
                t=tickers[0]; df=raw.copy()
                if isinstance(df.columns,pd.MultiIndex): df.columns=df.columns.get_level_values(1)
                df=df.drop(columns=["Adj Close"],errors="ignore")
                df.dropna(how="all",inplace=True)
                if len(df)>5: out[t]=df
            else:
                for t in tickers:
                    try:
                        if t in raw.columns.levels[0]:
                            df=raw[t].copy()
                            if isinstance(df.columns,pd.MultiIndex): df.columns=df.columns.get_level_values(-1)
                            df=df.drop(columns=["Adj Close"],errors="ignore")
                            df=df.dropna(how="all")
                            if len(df)>5: out[t]=df
                    except: pass
            break
        except Exception as e:
            if any(x in str(e) for x in ["Rate","429","Too Many","RateLimit"]):
                wait=30*(attempt+1); print(f"  Rate limit — wait {wait}s"); time.sleep(wait)
            else: break
    return out

def fetch_intraday(tickers, period="5d", interval="1h", retries=2):
    """Intraday fetcher (1h) — uses your working MultiIndex fix."""
    out = {}
    if not tickers: return out
    for attempt in range(retries+1):
        try:
            raw = yf.download(tickers, period=period, interval=interval,
                              group_by="ticker", auto_adjust=False,
                              progress=False, threads=True)
            if raw.empty: break
            if len(tickers)==1:
                t=tickers[0]; df=raw.copy()
                if isinstance(df.columns,pd.MultiIndex): df.columns=df.columns.get_level_values(1)
                df=df.drop(columns=["Adj Close"],errors="ignore")
                df.dropna(how="all",inplace=True)
                if len(df)>5: out[t]=df
            else:
                for t in tickers:
                    try:
                        if t in raw.columns.levels[0]:
                            df=raw[t].copy()
                            if isinstance(df.columns,pd.MultiIndex): df.columns=df.columns.get_level_values(-1)
                            df=df.drop(columns=["Adj Close"],errors="ignore")
                            df=df.dropna(how="all")
                            if len(df)>5: out[t]=df
                    except: pass
            break
        except Exception as e:
            if any(x in str(e) for x in ["Rate","429","Too Many","RateLimit"]):
                wait=30*(attempt+1); print(f"  Rate limit — wait {wait}s"); time.sleep(wait)
            else: break
    return out

print("fetch_batch (daily/weekly) + fetch_intraday (1h) ready")

fetch_batch (daily/weekly) + fetch_intraday (1h) ready

In [8]:
# CELL 6 — Daily scan functions
import numpy as np

def scan_bearish_momentum(d):
    try:
        if len(d)<52: return False
        c=_f(d["Close"].iloc[-1])
        return (c>50 and _f(rsi(d["Close"]).iloc[-1])<50
            and c<_f(d["Low"].iloc[-2])
            and c<_f(sma(d["Close"],50).iloc[-1])
            and _f(sma(d["Volume"],20).iloc[-1])>500000)
    except: return False

def scan_vcp(d, mktcap_m):
    try:
        if len(d)<252: return False
        c=_f(d["Close"].iloc[-1]); dvol=c*_f(sma(d["Volume"],20).iloc[-1])
        s200=_f(sma(d["Close"],200).iloc[-1]); s50=_f(sma(d["Close"],50).iloc[-1])
        c22=_f(d["Close"].iloc[-23]); c66=_f(d["Close"].iloc[-67])
        hi=_f(d["High"].rolling(252).max().iloc[-1])
        return ((c/c22>1.2 and mktcap_m>1 and dvol>30e6 and c>s200) or
                (c/c66>=1.3 and c>=1 and dvol>30e6 and c>s200) or
                (mktcap_m>=1000 and c>hi*0.75 and c>s50 and c>s200 and dvol>30e6))
    except: return False

def scan_satish_bullish(d, mktcap_m):
    try:
        if len(d)<47: return False
        c=_f(d["Close"].iloc[-1]); o=_f(d["Open"].iloc[-1])
        lo=_f(d["Low"].iloc[-1]); v=_f(d["Volume"].iloc[-1])
        pc=_f(d["Close"].iloc[-2]); pl=_f(d["Low"].iloc[-2]); ph=_f(d["High"].iloc[-2])
        pivot=(ph+pl+pc)/3; r=rsi(d["Close"])
        return (mktcap_m>=1000 and c>=100 and c>pivot
            and v>_f(sma(d["Volume"],10).iloc[-1])
            and lo>pl and c>pc and c>o
            and _f(sma(d["Close"],9).iloc[-1])>_f(ema(d["Close"],45).iloc[-1])
            and _f(r.iloc[-3])>_f(r.iloc[-2])
            and (c-pc)/pc*100>1 and _f(r.iloc[-1])>30 and v>100000)
    except: return False

def scan_hardik(d, w, mktcap_m, is_nifty=False):
    # mktcap threshold: 5000 crores for Nifty (~$600M), 5000 USD millions for US ($5B)
    try:
        if len(d)<12 or len(w)<16: return False
        return (_f(rsi(w["Close"]).iloc[-1])>50
            and _f(d["Close"].iloc[-1])>_f(sma(d["Close"],10).iloc[-1])
            and _f(sma(d["Close"],10).iloc[-6])>_f(d["Close"].iloc[-6])
            and _f(d["Close"].iloc[-2])<_f(d["Open"].iloc[-2])
            and _f(d["Close"].iloc[-1])>_f(d["Open"].iloc[-1])
            and mktcap_m>5000)
    except: return False

def scan_nr6(d):
    try:
        if len(d)<8: return False
        r0=_range(d,0)
        return all(r0<_range(d,i) for i in range(1,7))
    except: return False

def scan_rocket_base(d):
    try:
        if len(d)<92: return False
        c=_f(d["Close"].iloc[-1])
        if c<=30 or _f(sma(d["Volume"],50).iloc[-1])<50000: return False
        return (c>=_f(d["Low"].iloc[-6])*1.2 or
                c>=_f(d["Low"].iloc[-31])*1.3 or
                c>=_f(d["Low"].iloc[-91])*1.3)
    except: return False

def scan_ep_breakout(d):
    try:
        if len(d)<130: return False
        max5=_f(d["Close"].rolling(5).max().iloc[-1])
        max120_6ago=_f(d["Close"].rolling(120).max().iloc[-7])
        return (max5>max120_6ago*1.05
            and _f(d["Volume"].iloc[-1])>_f(sma(d["Volume"],5).iloc[-1])
            and _f(d["Close"].iloc[-1])>_f(d["Close"].iloc[-2]))
    except: return False

def scan_20day_high(d, is_us=True):
    if not is_us: return False
    try:
        if len(d)<21: return False
        return _f(d["Close"].iloc[-1])>=_f(d["High"].rolling(20).max().iloc[-1])
    except: return False

def scan_2month_high(d, is_us=True):
    if not is_us: return False
    try:
        if len(d)<43: return False
        return _f(d["Close"].iloc[-1])>=_f(d["High"].rolling(42).max().iloc[-1])
    except: return False

def scan_gapup(d):
    try:
        if len(d)<2: return False
        return _f(d["Open"].iloc[-1])>=_f(d["Close"].iloc[-2])*1.03
    except: return False

def scan_up4pct(d):
    try:
        if len(d)<2: return False
        c=_f(d["Close"].iloc[-1]); o=_f(d["Open"].iloc[-1])
        return (c-o)/o>=0.04
    except: return False

print("Daily scan functions ready (11 scans)")

Daily scan functions ready (11 scans)

In [9]:
# CELL 7 — Daily scan runner
import time

DAILY_SCAN_KEYS = [
    "bearish_momentum","vcp_setup","satish_bullish","hardik",
    "nr6","rocket_base","ep_breakout","high_20d","high_2month",
    "gapup_3pct","up_4pct"
]

def run_daily_scans(tickers, label):
    is_nifty = label=="Nifty 500"
    is_us    = not is_nifty
    hits = {k:[] for k in DAILY_SCAN_KEYS}
    batches=[tickers[i:i+BATCH_SIZE] for i in range(0,len(tickers),BATCH_SIZE)]
    total=len(batches)
    print(f"Scanning {label} — {len(tickers)} tickers, {total} batches")
    for n,batch in enumerate(batches):
        print(f"  Batch {n+1}/{total}",end="\r")
        daily  = fetch_batch(batch,"2y","1d")
        weekly = fetch_batch(batch,"5y","1wk")
        for t in batch:
            d=daily.get(t); w=weekly.get(t)
            if d is None or len(d)<10: continue
            try:
                c=float(d["Close"].iloc[-1]); av=float(sma(d["Volume"],20).iloc[-1])
                mktcap = c*av*30/(1e7 if is_nifty else 1e6)
            except: mktcap=0
            if scan_bearish_momentum(d):                     hits["bearish_momentum"].append(t)
            if scan_vcp(d,mktcap):                           hits["vcp_setup"].append(t)
            if scan_satish_bullish(d,mktcap):                hits["satish_bullish"].append(t)
            if w is not None and scan_hardik(d,w,mktcap,is_nifty): hits["hardik"].append(t)
            if scan_nr6(d):                                  hits["nr6"].append(t)
            if scan_rocket_base(d):                          hits["rocket_base"].append(t)
            if scan_ep_breakout(d):                          hits["ep_breakout"].append(t)
            if scan_20day_high(d,is_us):                     hits["high_20d"].append(t)
            if scan_2month_high(d,is_us):                    hits["high_2month"].append(t)
            if scan_gapup(d):                                hits["gapup_3pct"].append(t)
            if scan_up4pct(d):                               hits["up_4pct"].append(t)
        time.sleep(SLEEP_BETWEEN_BATCHES)
    print(f"\n{label} done")
    return hits

print("Daily runner ready")

Daily runner ready

In [ ]:
# CELL 8 — RUN DAILY SCANS
# S&P 500: ~10 min | Russell 2000: ~20 min | Nifty: ~10 min
from datetime import datetime
start=datetime.now()
print(f"Started: {start.strftime('%H:%M:%S')}")
sp500_hits  = run_daily_scans(sp500,      "S&P 500")
r2000_hits  = run_daily_scans(r2000_only, "Russell 2000")
nifty_hits  = run_daily_scans(nifty500,   "Nifty 500") if INCLUDE_NIFTY else {k:[] for k in DAILY_SCAN_KEYS}
print(f"Done in ~{(datetime.now()-start).seconds//60} min")

# ── Save website data to repository ─────────────────────────
import pandas as pd
from pathlib import Path
from datetime import datetime

OUTDIR=Path("public/data"); OUTDIR.mkdir(parents=True,exist_ok=True)
_ts=datetime.now().strftime("%Y-%m-%d %H:%M")
_rows=[]
_labels={"bearish_momentum":"Bearish Momentum","vcp_setup":"VCP Setup","satish_bullish":"Satish Bullish","hardik":"Hardik Scan","nr6":"NR6 Narrowest Range","rocket_base":"Rocket Base","ep_breakout":"EP Breakout","high_20d":"20-Day High (US)","high_2month":"2-Month High (US)","gapup_3pct":"Gap Up 3pct","up_4pct":"Up 4pct"}
for _k in DAILY_SCAN_KEYS:
    _label=_labels.get(_k,_k)
    for _t in sp500_hits.get(_k,[]): _rows.append({"Scan":_label,"Ticker":_t,"Universe":"S&P 500","Updated":_ts})
    for _t in r2000_hits.get(_k,[]): _rows.append({"Scan":_label,"Ticker":_t,"Universe":"Russell 2000","Updated":_ts})
    for _t in nifty_hits.get(_k,[]): _rows.append({"Scan":_label,"Ticker":_t,"Universe":"Nifty 500","Updated":_ts})
_daily_df=pd.DataFrame(_rows) if _rows else pd.DataFrame(columns=["Scan","Ticker","Universe","Updated"])
_daily_df.to_json(OUTDIR/"daily.json",orient="records",indent=2,date_format="iso")
_daily_df.to_excel(OUTDIR/"daily.xlsx",index=False)
print(f"✅ Daily JSON: {OUTDIR/'daily.json'} ({len(_daily_df)} rows)")
print(f"✅ Daily Excel: {OUTDIR/'daily.xlsx'} ({len(_daily_df)} rows)")

Started: 12:51:00
Scanning S&P 500 — 503 tickers, 13 batches

S&P 500 done
Scanning Russell 2000 — 2000 tickers, 50 batches

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AHL"}}}
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['AKO']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:['AHL']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: AHL"}}}
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['AKO']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')
ERROR:yfinance:['AHL']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ANG']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ANG']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ATH']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ATH']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['BF']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['BF']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['BML']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['BML']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['BRK']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['BRK']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['CFTR', 'CDR']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['CFTR', 'CDR']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ETI']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ETI']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['GLOP']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['GLOP']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ICR']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['ICR']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['OAK']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['OAK']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['PRIF']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['PRIF']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['SCE']: YFPricesMissingError('possibly delisted; no price data found  (period=2y)')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['SCE']: YFPricesMissingError('possibly delisted; no price data found  (period=5y)')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['SEAL']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['SEAL']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['TRTN']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
1 Failed download:
ERROR:yfinance:['TRTN']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

Russell 2000 done
Scanning Nifty 500 — 1483 tickers, 38 batches

ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['BOM.3MINDIA', 'BOM.360ONE']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
2 Failed downloads:
ERROR:yfinance:['BOM.3MINDIA', 'BOM.360ONE']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532811', 'BOM.526881', 'BOM.532268', 'BOM.543534', 'BOM.540691', 'BOM.524208', 'BOM.539254', 'BOM.500410', 'BOM.500187', 'BOM.541988', 'BOM.500003', 'BOM.544283', 'BOM.543349', 'BOM.532683', 'BOM.524348', 'BOM.535755', 'BOM.533096', 'BOM.542772', 'BOM.532762', 'BOM.542752', 'BOM.544280', 'BOM.544466', 'BOM.544407', 'BOM.544403', 'BOM.523395', 'BOM.544176', 'BOM.542066', 'BOM.500488', 'BOM.543748', 'BOM.500040', 'BOM.512599', 'BOM.544634', 'BOM.540205', 'BOM.500002', 'BOM.519183', 'BOM.540025', 'BOM.532921', 'BOM.541450', 'BOM.532331', 'BOM.543374']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532811', 'BOM.526881', 'BOM.543534', 'BOM.532268', 'BOM.540691', 'BOM.524208', 'BOM.500410', 'BOM.539254', 'BOM.500187', 'BOM.541988', 'BOM.544283', 'BOM.500003', 'BOM.543349', 'BOM.532683', 'BOM.535755', 'BOM.524348', 'BOM.542772', 'BOM.533096', 'BOM.532762', 'BOM.542752', 'BOM.544466', 'BOM.544280', 'BOM.544403', 'BOM.544407', 'BOM.544176', 'BOM.523395', 'BOM.500488', 'BOM.542066', 'BOM.500040', 'BOM.543748', 'BOM.512599', 'BOM.544634', 'BOM.500002', 'BOM.540205', 'BOM.519183', 'BOM.540025', 'BOM.532921', 'BOM.541450', 'BOM.543374', 'BOM.532331']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.544022', 'BOM.508869', 'BOM.543335', 'BOM.523694', 'BOM.543657', 'BOM.515030', 'BOM.544111', 'BOM.521070', 'BOM.500101', 'BOM.539523', 'BOM.540975', 'BOM.532259', 'BOM.543322', 'BOM.500877', 'BOM.506820', 'BOM.544356', 'BOM.543235', 'BOM.532830', 'BOM.533573', 'BOM.506767', 'BOM.544449', 'BOM.540879', 'BOM.523716', 'BOM.544203', 'BOM.543415', 'BOM.500820', 'BOM.506235', 'BOM.542919', 'BOM.526433', 'BOM.500477', 'BOM.500008', 'BOM.542484', 'BOM.500425', 'BOM.540902', 'BOM.533271', 'BOM.544397', 'BOM.533758', 'BOM.544222', 'BOM.532493', 'BOM.515055']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.544022', 'BOM.508869', 'BOM.523694', 'BOM.543335', 'BOM.543657', 'BOM.515030', 'BOM.544111', 'BOM.521070', 'BOM.539523', 'BOM.500101', 'BOM.540975', 'BOM.532259', 'BOM.543322', 'BOM.500877', 'BOM.506820', 'BOM.544356', 'BOM.543235', 'BOM.532830', 'BOM.533573', 'BOM.506767', 'BOM.544449', 'BOM.540879', 'BOM.544203', 'BOM.523716', 'BOM.500820', 'BOM.543415', 'BOM.542919', 'BOM.506235', 'BOM.526433', 'BOM.500477', 'BOM.542484', 'BOM.500008', 'BOM.540902', 'BOM.500425', 'BOM.544397', 'BOM.533271', 'BOM.544222', 'BOM.533758', 'BOM.515055', 'BOM.532493']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532525', 'BOM.544061', 'BOM.532977', 'BOM.500031', 'BOM.544181', 'BOM.505010', 'BOM.543896', 'BOM.500032', 'BOM.532149', 'BOM.533229', 'BOM.540376', 'BOM.500034', 'BOM.532395', 'BOM.532668', 'BOM.506285', 'BOM.512573', 'BOM.543458', 'BOM.500490', 'BOM.500039', 'BOM.532978', 'BOM.544527', 'BOM.530999', 'BOM.544209', 'BOM.500042', 'BOM.532134', 'BOM.500027', 'BOM.532215', 'BOM.544042', 'BOM.544405', 'BOM.500038', 'BOM.500043', 'BOM.523319', 'BOM.502355', 'BOM.541153', 'BOM.540611', 'BOM.524804', 'BOM.531112', 'BOM.539807', 'BOM.544252', 'BOM.539177']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532525', 'BOM.544061', 'BOM.532977', 'BOM.500031', 'BOM.505010', 'BOM.544181', 'BOM.500032', 'BOM.543896', 'BOM.532149', 'BOM.533229', 'BOM.540376', 'BOM.500034', 'BOM.532668', 'BOM.532395', 'BOM.512573', 'BOM.506285', 'BOM.543458', 'BOM.500490', 'BOM.500039', 'BOM.532978', 'BOM.544527', 'BOM.530999', 'BOM.500042', 'BOM.544209', 'BOM.532134', 'BOM.500027', 'BOM.532215', 'BOM.544042', 'BOM.500038', 'BOM.544405', 'BOM.500043', 'BOM.523319', 'BOM.502355', 'BOM.541153', 'BOM.540611', 'BOM.524804', 'BOM.539807', 'BOM.531112', 'BOM.539177', 'BOM.544252']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500103', 'BOM.532400', 'BOM.500335', 'BOM.532834', 'BOM.541143', 'BOM.544009', 'BOM.500020', 'BOM.500067', 'BOM.543212', 'BOM.503960', 'BOM.544226', 'BOM.509480', 'BOM.532929', 'BOM.533267', 'BOM.500547', 'BOM.500493', 'BOM.544162', 'BOM.532454', 'BOM.500048', 'BOM.544484', 'BOM.543523', 'BOM.511196', 'BOM.544603', 'BOM.544580', 'BOM.500825', 'BOM.500463', 'BOM.532523', 'BOM.532483', 'BOM.502219', 'BOM.500530', 'BOM.540710', 'BOM.544288', 'BOM.543653', 'BOM.540073', 'BOM.526612', 'BOM.544583', 'BOM.500049', 'BOM.543425', 'BOM.523398', 'BOM.500052']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500103', 'BOM.532400', 'BOM.532834', 'BOM.500335', 'BOM.544009', 'BOM.541143', 'BOM.500020', 'BOM.500067', 'BOM.503960', 'BOM.543212', 'BOM.544226', 'BOM.509480', 'BOM.532929', 'BOM.533267', 'BOM.500493', 'BOM.500547', 'BOM.532454', 'BOM.544162', 'BOM.500048', 'BOM.544484', 'BOM.543523', 'BOM.511196', 'BOM.544603', 'BOM.544580', 'BOM.500463', 'BOM.532483', 'BOM.500825', 'BOM.502219', 'BOM.532523', 'BOM.544288', 'BOM.500530', 'BOM.540710', 'BOM.543653', 'BOM.544583', 'BOM.540073', 'BOM.526612', 'BOM.543425', 'BOM.523398', 'BOM.500049', 'BOM.500052']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.506395', 'BOM.524091', 'BOM.504973', 'BOM.532885', 'BOM.513375', 'BOM.500878', 'BOM.532541', 'BOM.532548', 'BOM.544614', 'BOM.543441', 'BOM.500093', 'BOM.532756', 'BOM.533278', 'BOM.524742', 'BOM.500830', 'BOM.500110', 'BOM.511243', 'BOM.543064', 'BOM.542399', 'BOM.544223', 'BOM.500085', 'BOM.543336', 'BOM.532443', 'BOM.543318', 'BOM.531358', 'BOM.531595', 'BOM.500087', 'BOM.500870', 'BOM.540678', 'BOM.500084', 'BOM.509496', 'BOM.544012', 'BOM.544644', 'BOM.534804', 'BOM.531344', 'BOM.532210', 'BOM.543333', 'BOM.519600', 'BOM.543960', 'BOM.543232']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.524091', 'BOM.506395', 'BOM.532885', 'BOM.504973', 'BOM.500878', 'BOM.513375', 'BOM.532548', 'BOM.532541', 'BOM.544614', 'BOM.543441', 'BOM.500093', 'BOM.532756', 'BOM.533278', 'BOM.524742', 'BOM.500830', 'BOM.500110', 'BOM.511243', 'BOM.543064', 'BOM.544223', 'BOM.542399', 'BOM.500085', 'BOM.543336', 'BOM.532443', 'BOM.543318', 'BOM.531595', 'BOM.531358', 'BOM.500087', 'BOM.500870', 'BOM.540678', 'BOM.500084', 'BOM.544012', 'BOM.509496', 'BOM.534804', 'BOM.544644', 'BOM.531344', 'BOM.532210', 'BOM.519600', 'BOM.543333', 'BOM.543960', 'BOM.543232']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.506401', 'BOM.532868', 'BOM.540701', 'BOM.532927', 'BOM.532175', 'BOM.505200', 'BOM.539876', 'BOM.532922', 'BOM.544350', 'BOM.500124', 'BOM.500480', 'BOM.543306', 'BOM.500125', 'BOM.543276', 'BOM.542216', 'BOM.522163', 'BOM.505242', 'BOM.532772', 'BOM.543428', 'BOM.500645', 'BOM.542867', 'BOM.530843', 'BOM.543330', 'BOM.500096', 'BOM.544045', 'BOM.543812', 'BOM.541770', 'BOM.532488', 'BOM.543529', 'BOM.523367', 'BOM.500092', 'BOM.540047', 'BOM.540699', 'BOM.507717', 'BOM.543650', 'BOM.533151', 'BOM.539524', 'BOM.543933', 'BOM.544439', 'BOM.532528']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.506401', 'BOM.532868', 'BOM.532927', 'BOM.540701', 'BOM.532175', 'BOM.505200', 'BOM.532922', 'BOM.539876', 'BOM.544350', 'BOM.500124', 'BOM.543306', 'BOM.500480', 'BOM.500125', 'BOM.543276', 'BOM.522163', 'BOM.542216', 'BOM.532772', 'BOM.505242', 'BOM.500645', 'BOM.543428', 'BOM.542867', 'BOM.530843', 'BOM.543330', 'BOM.500096', 'BOM.544045', 'BOM.543812', 'BOM.532488', 'BOM.541770', 'BOM.523367', 'BOM.543529', 'BOM.500092', 'BOM.540047', 'BOM.507717', 'BOM.540699', 'BOM.543650', 'BOM.533151', 'BOM.543933', 'BOM.539524', 'BOM.544439', 'BOM.532528']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500144', 'BOM.500123', 'BOM.505700', 'BOM.543482', 'BOM.500135', 'BOM.500840', 'BOM.531508', 'BOM.500086', 'BOM.526227', 'BOM.533333', 'BOM.500128', 'BOM.500495', 'BOM.522074', 'BOM.544421', 'BOM.543983', 'BOM.500940', 'BOM.531162', 'BOM.543533', 'BOM.541557', 'BOM.500133', 'BOM.543243', 'BOM.543532', 'BOM.544210', 'BOM.532178', 'BOM.531599', 'BOM.544095', 'BOM.544608', 'BOM.540153', 'BOM.532768', 'BOM.500469', 'BOM.543332', 'BOM.544122', 'BOM.540596', 'BOM.544290', 'BOM.505744', 'BOM.523127', 'BOM.544027', 'BOM.543320', 'BOM.532832', 'BOM.543626']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500144', 'BOM.500123', 'BOM.543482', 'BOM.505700', 'BOM.500840', 'BOM.500135', 'BOM.531508', 'BOM.500086', 'BOM.526227', 'BOM.533333', 'BOM.500495', 'BOM.500128', 'BOM.544421', 'BOM.522074', 'BOM.500940', 'BOM.543983', 'BOM.531162', 'BOM.543533', 'BOM.500133', 'BOM.541557', 'BOM.543243', 'BOM.543532', 'BOM.532178', 'BOM.544210', 'BOM.544095', 'BOM.531599', 'BOM.544608', 'BOM.540153', 'BOM.500469', 'BOM.532768', 'BOM.544122', 'BOM.543332', 'BOM.544290', 'BOM.540596', 'BOM.505744', 'BOM.523127', 'BOM.544027', 'BOM.543320', 'BOM.543626', 'BOM.532832']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532809', 'BOM.500033', 'BOM.532285', 'BOM.500660', 'BOM.540743', 'BOM.544613', 'BOM.505714', 'BOM.532424', 'BOM.524743', 'BOM.500171', 'BOM.543384', 'BOM.540935', 'BOM.532754', 'BOM.544179', 'BOM.532726', 'BOM.543654', 'BOM.500655', 'BOM.532296', 'BOM.522275', 'BOM.544030', 'BOM.533104', 'BOM.505255', 'BOM.509557', 'BOM.543401', 'BOM.500163', 'BOM.543245', 'BOM.507815', 'BOM.543652', 'BOM.526367', 'BOM.500150', 'BOM.532155', 'BOM.543663', 'BOM.543490', 'BOM.543489', 'BOM.514167', 'BOM.540755', 'BOM.542011', 'BOM.532843', 'BOM.532734', 'BOM.543317']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500033', 'BOM.532809', 'BOM.500660', 'BOM.532285', 'BOM.540743', 'BOM.544613', 'BOM.532424', 'BOM.505714', 'BOM.500171', 'BOM.524743', 'BOM.543384', 'BOM.540935', 'BOM.544179', 'BOM.532754', 'BOM.532726', 'BOM.543654', 'BOM.500655', 'BOM.532296', 'BOM.544030', 'BOM.522275', 'BOM.533104', 'BOM.505255', 'BOM.543401', 'BOM.509557', 'BOM.500163', 'BOM.543245', 'BOM.507815', 'BOM.543652', 'BOM.500150', 'BOM.526367', 'BOM.532155', 'BOM.543663', 'BOM.543489', 'BOM.543490', 'BOM.540755', 'BOM.514167', 'BOM.542011', 'BOM.532843', 'BOM.532734', 'BOM.543317']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.509488', 'BOM.500620', 'BOM.543600', 'BOM.509079', 'BOM.517354', 'BOM.533282', 'BOM.533150', 'BOM.538979', 'BOM.544140', 'BOM.517271', 'BOM.544801', 'BOM.538567', 'BOM.500670', 'BOM.532482', 'BOM.524226', 'BOM.505710', 'BOM.500300', 'BOM.526797', 'BOM.544057', 'BOM.541019', 'BOM.517300', 'BOM.531531', 'BOM.506076', 'BOM.543227', 'BOM.526729', 'BOM.532630', 'BOM.532181', 'BOM.530655', 'BOM.533248', 'BOM.500164', 'BOM.533162', 'BOM.530001', 'BOM.500168', 'BOM.501455', 'BOM.542857', 'BOM.539725', 'BOM.508486', 'BOM.542812', 'BOM.500690', 'BOM.539336']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500620', 'BOM.509488', 'BOM.509079', 'BOM.543600', 'BOM.517354', 'BOM.533282', 'BOM.533150', 'BOM.538979', 'BOM.544140', 'BOM.517271', 'BOM.544801', 'BOM.538567', 'BOM.500670', 'BOM.532482', 'BOM.505710', 'BOM.524226', 'BOM.526797', 'BOM.500300', 'BOM.541019', 'BOM.544057', 'BOM.517300', 'BOM.531531', 'BOM.506076', 'BOM.543227', 'BOM.526729', 'BOM.532630', 'BOM.532181', 'BOM.530655', 'BOM.500164', 'BOM.533248', 'BOM.533162', 'BOM.530001', 'BOM.500168', 'BOM.501455', 'BOM.542857', 'BOM.539725', 'BOM.542812', 'BOM.508486', 'BOM.500690', 'BOM.539336']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.543259', 'BOM.540777', 'BOM.500292', 'BOM.500180', 'BOM.540530', 'BOM.500116', 'BOM.540716', 'BOM.522064', 'BOM.540133', 'BOM.500183', 'BOM.543242', 'BOM.500188', 'BOM.500696', 'BOM.542905', 'BOM.519126', 'BOM.519552', 'BOM.544429', 'BOM.532859', 'BOM.509631', 'BOM.524735', 'BOM.522215', 'BOM.500185', 'BOM.500182', 'BOM.541729', 'BOM.500184', 'BOM.544658', 'BOM.532835', 'BOM.543187', 'BOM.544362', 'BOM.544014', 'BOM.544274', 'BOM.500104', 'BOM.541154', 'BOM.539787', 'BOM.513599', 'BOM.500440', 'BOM.532174', 'BOM.517174', 'BOM.500186', 'BOM.532281']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.543259', 'BOM.540777', 'BOM.500180', 'BOM.500292', 'BOM.500116', 'BOM.540530', 'BOM.522064', 'BOM.540716', 'BOM.540133', 'BOM.500183', 'BOM.500188', 'BOM.543242', 'BOM.500696', 'BOM.542905', 'BOM.519126', 'BOM.519552', 'BOM.544429', 'BOM.532859', 'BOM.509631', 'BOM.524735', 'BOM.522215', 'BOM.500185', 'BOM.500182', 'BOM.541729', 'BOM.544658', 'BOM.500184', 'BOM.532835', 'BOM.543187', 'BOM.544014', 'BOM.544362', 'BOM.544274', 'BOM.500104', 'BOM.541154', 'BOM.539787', 'BOM.500440', 'BOM.513599', 'BOM.517174', 'BOM.532174', 'BOM.500186', 'BOM.532281']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.543311', 'BOM.532612', 'BOM.532514', 'BOM.500210', 'BOM.542773', 'BOM.543258', 'BOM.533047', 'BOM.500106', 'BOM.544026', 'BOM.534816', 'BOM.544044', 'BOM.543667', 'BOM.532189', 'BOM.544046', 'BOM.532187', 'BOM.541336', 'BOM.538835', 'BOM.542830', 'BOM.540750', 'BOM.544172', 'BOM.500209', 'BOM.544836', 'BOM.539083', 'BOM.544067', 'BOM.532388', 'BOM.532777', 'BOM.532851', 'BOM.530965', 'BOM.543932', 'BOM.521016', 'BOM.532150', 'BOM.539056', 'BOM.542726', 'BOM.532636', 'BOM.539437', 'BOM.505726', 'BOM.500201', 'BOM.530005', 'BOM.532814', 'BOM.543257']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532612', 'BOM.543311', 'BOM.500210', 'BOM.532514', 'BOM.543258', 'BOM.542773', 'BOM.533047', 'BOM.500106', 'BOM.544026', 'BOM.534816', 'BOM.543667', 'BOM.544044', 'BOM.532189', 'BOM.544046', 'BOM.532187', 'BOM.541336', 'BOM.542830', 'BOM.538835', 'BOM.544172', 'BOM.540750', 'BOM.544836', 'BOM.500209', 'BOM.544067', 'BOM.539083', 'BOM.532388', 'BOM.532777', 'BOM.530965', 'BOM.532851', 'BOM.521016', 'BOM.543932', 'BOM.539056', 'BOM.532150', 'BOM.532636', 'BOM.542726', 'BOM.505726', 'BOM.539437', 'BOM.500201', 'BOM.530005', 'BOM.543257', 'BOM.532814']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.533033', 'BOM.532627', 'BOM.523405', 'BOM.532605', 'BOM.544309', 'BOM.533148', 'BOM.543994', 'BOM.543940', 'BOM.531543', 'BOM.500228', 'BOM.512237', 'BOM.544480', 'BOM.524164', 'BOM.532947', 'BOM.532976', 'BOM.520051', 'BOM.500227', 'BOM.500378', 'BOM.539448', 'BOM.524494', 'BOM.500214', 'BOM.532286', 'BOM.532209', 'BOM.544325', 'BOM.532644', 'BOM.544118', 'BOM.532162', 'BOM.500875', 'BOM.530007', 'BOM.544537', 'BOM.500710', 'BOM.544311', 'BOM.532642', 'BOM.532940', 'BOM.523610', 'BOM.522285', 'BOM.532508', 'BOM.500380', 'BOM.541956', 'BOM.500219']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.533033', 'BOM.532627', 'BOM.523405', 'BOM.532605', 'BOM.533148', 'BOM.544309', 'BOM.543940', 'BOM.543994', 'BOM.531543', 'BOM.500228', 'BOM.512237', 'BOM.544480', 'BOM.532947', 'BOM.524164', 'BOM.520051', 'BOM.532976', 'BOM.500378', 'BOM.500227', 'BOM.524494', 'BOM.539448', 'BOM.500214', 'BOM.532286', 'BOM.544325', 'BOM.532209', 'BOM.532644', 'BOM.544118', 'BOM.532162', 'BOM.500875', 'BOM.530007', 'BOM.544537', 'BOM.544311', 'BOM.500710', 'BOM.532642', 'BOM.532940', 'BOM.522285', 'BOM.523610', 'BOM.500380', 'BOM.532508', 'BOM.541956', 'BOM.500219']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.533155', 'BOM.532926', 'BOM.533293', 'BOM.543980', 'BOM.522287', 'BOM.520057', 'BOM.543273', 'BOM.532942', 'BOM.543720', 'BOM.532468', 'BOM.532652', 'BOM.543278', 'BOM.532732', 'BOM.505890', 'BOM.530019', 'BOM.543664', 'BOM.500243', 'BOM.544081', 'BOM.533272', 'BOM.524019', 'BOM.534600', 'BOM.500233', 'BOM.500165', 'BOM.521248', 'BOM.500241', 'BOM.543669', 'BOM.544423', 'BOM.532889', 'BOM.500245', 'BOM.505283', 'BOM.544129', 'BOM.540680', 'BOM.543271', 'BOM.532899', 'BOM.535648', 'BOM.532714', 'BOM.532054', 'BOM.517569', 'BOM.500235', 'BOM.532967']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.533155', 'BOM.532926', 'BOM.533293', 'BOM.543980', 'BOM.522287', 'BOM.520057', 'BOM.532942', 'BOM.543273', 'BOM.532468', 'BOM.543720', 'BOM.543278', 'BOM.532652', 'BOM.505890', 'BOM.532732', 'BOM.543664', 'BOM.530019', 'BOM.500243', 'BOM.544081', 'BOM.524019', 'BOM.533272', 'BOM.500233', 'BOM.534600', 'BOM.521248', 'BOM.500165', 'BOM.500241', 'BOM.543669', 'BOM.544423', 'BOM.532889', 'BOM.500245', 'BOM.505283', 'BOM.540680', 'BOM.544129', 'BOM.532899', 'BOM.543271', 'BOM.535648', 'BOM.532714', 'BOM.532054', 'BOM.517569', 'BOM.500235', 'BOM.532967']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.541233', 'BOM.500257', 'BOM.533519', 'BOM.543526', 'BOM.544576', 'BOM.544263', 'BOM.500249', 'BOM.543398', 'BOM.543714', 'BOM.540115', 'BOM.512455', 'BOM.539992', 'BOM.500252', 'BOM.517206', 'BOM.500108', 'BOM.500247', 'BOM.543328', 'BOM.523323', 'BOM.532924', 'BOM.530813', 'BOM.500253', 'BOM.500250', 'BOM.544600', 'BOM.526947', 'BOM.540222', 'BOM.532796', 'BOM.523457', 'BOM.500266', 'BOM.543277', 'BOM.512463', 'BOM.543308', 'BOM.543287', 'BOM.542651', 'BOM.539957', 'BOM.500510', 'BOM.540005', 'BOM.542323', 'BOM.544192', 'BOM.544408', 'BOM.532783']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500257', 'BOM.541233', 'BOM.533519', 'BOM.543526', 'BOM.544263', 'BOM.544576', 'BOM.500249', 'BOM.543398', 'BOM.543714', 'BOM.540115', 'BOM.512455', 'BOM.539992', 'BOM.500252', 'BOM.517206', 'BOM.500247', 'BOM.500108', 'BOM.523323', 'BOM.543328', 'BOM.532924', 'BOM.530813', 'BOM.500250', 'BOM.500253', 'BOM.544600', 'BOM.526947', 'BOM.532796', 'BOM.540222', 'BOM.523457', 'BOM.500266', 'BOM.543277', 'BOM.512463', 'BOM.543308', 'BOM.543287', 'BOM.539957', 'BOM.542651', 'BOM.500510', 'BOM.540005', 'BOM.544192', 'BOM.542323', 'BOM.544408', 'BOM.532783']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.513377', 'BOM.544088', 'BOM.533080', 'BOM.538962', 'BOM.500288', 'BOM.524404', 'BOM.540749', 'BOM.500290', 'BOM.522249', 'BOM.532313', 'BOM.531213', 'BOM.531642', 'BOM.544587', 'BOM.532892', 'BOM.523704', 'BOM.543498', 'BOM.532720', 'BOM.532440', 'BOM.543426', 'BOM.542650', 'BOM.542597', 'BOM.543427', 'BOM.544008', 'BOM.533286', 'BOM.500271', 'BOM.500265', 'BOM.526299', 'BOM.543220', 'BOM.543253', 'BOM.500520', 'BOM.541195', 'BOM.543904', 'BOM.532500', 'BOM.541974', 'BOM.544632', 'BOM.533088', 'BOM.533169', 'BOM.500109', 'BOM.540768', 'BOM.543237']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.544088', 'BOM.513377', 'BOM.533080', 'BOM.538962', 'BOM.524404', 'BOM.500288', 'BOM.540749', 'BOM.500290', 'BOM.522249', 'BOM.532313', 'BOM.531213', 'BOM.531642', 'BOM.532892', 'BOM.544587', 'BOM.543498', 'BOM.523704', 'BOM.532720', 'BOM.532440', 'BOM.543426', 'BOM.542650', 'BOM.543427', 'BOM.542597', 'BOM.533286', 'BOM.544008', 'BOM.500265', 'BOM.500271', 'BOM.526299', 'BOM.543220', 'BOM.543253', 'BOM.500520', 'BOM.543904', 'BOM.541195', 'BOM.541974', 'BOM.532500', 'BOM.544632', 'BOM.533088', 'BOM.533169', 'BOM.500109', 'BOM.543237', 'BOM.540768']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.534091', 'BOM.532504', 'BOM.544055', 'BOM.532555', 'BOM.505355', 'BOM.530367', 'BOM.513023', 'BOM.543280', 'BOM.500790', 'BOM.533398', 'BOM.524558', 'BOM.500294', 'BOM.540900', 'BOM.508989', 'BOM.534309', 'BOM.543952', 'BOM.500307', 'BOM.544286', 'BOM.523385', 'BOM.532798', 'BOM.526371', 'BOM.500460', 'BOM.544467', 'BOM.523630', 'BOM.500730', 'BOM.539551', 'BOM.524816', 'BOM.544647', 'BOM.543270', 'BOM.500672', 'BOM.513683', 'BOM.540767', 'BOM.543768', 'BOM.543945', 'BOM.524709', 'BOM.533098', 'BOM.542665', 'BOM.544289', 'BOM.532698', 'BOM.532234']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.534091', 'BOM.532504', 'BOM.544055', 'BOM.532555', 'BOM.505355', 'BOM.530367', 'BOM.513023', 'BOM.543280', 'BOM.500790', 'BOM.533398', 'BOM.524558', 'BOM.500294', 'BOM.508989', 'BOM.540900', 'BOM.534309', 'BOM.543952', 'BOM.500307', 'BOM.544286', 'BOM.523385', 'BOM.532798', 'BOM.526371', 'BOM.500460', 'BOM.523630', 'BOM.544467', 'BOM.500730', 'BOM.539551', 'BOM.544647', 'BOM.524816', 'BOM.500672', 'BOM.543270', 'BOM.540767', 'BOM.513683', 'BOM.543945', 'BOM.543768', 'BOM.533098', 'BOM.524709', 'BOM.544289', 'BOM.542665', 'BOM.532234', 'BOM.532698']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.543334', 'BOM.506590', 'BOM.544256', 'BOM.543988', 'BOM.530305', 'BOM.532827', 'BOM.544595', 'BOM.534809', 'BOM.544418', 'BOM.532522', 'BOM.500368', 'BOM.532900', 'BOM.532439', 'BOM.543367', 'BOM.533581', 'BOM.539889', 'BOM.530135', 'BOM.544225', 'BOM.538730', 'BOM.500312', 'BOM.523642', 'BOM.543396', 'BOM.533106', 'BOM.533273', 'BOM.532466', 'BOM.541301', 'BOM.500680', 'BOM.531209', 'BOM.544609', 'BOM.543390', 'BOM.500331', 'BOM.532808', 'BOM.524372', 'BOM.544645', 'BOM.543530', 'BOM.531120', 'BOM.535754', 'BOM.500314', 'BOM.544292', 'BOM.533179']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.506590', 'BOM.543334', 'BOM.544256', 'BOM.543988', 'BOM.530305', 'BOM.532827', 'BOM.544595', 'BOM.534809', 'BOM.532522', 'BOM.544418', 'BOM.532900', 'BOM.500368', 'BOM.543367', 'BOM.532439', 'BOM.533581', 'BOM.539889', 'BOM.530135', 'BOM.544225', 'BOM.538730', 'BOM.500312', 'BOM.523642', 'BOM.543396', 'BOM.533106', 'BOM.533273', 'BOM.532466', 'BOM.541301', 'BOM.531209', 'BOM.500680', 'BOM.543390', 'BOM.544609', 'BOM.532808', 'BOM.500331', 'BOM.524372', 'BOM.544645', 'BOM.531120', 'BOM.543530', 'BOM.500314', 'BOM.535754', 'BOM.533179', 'BOM.544292']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.524000', 'BOM.539006', 'BOM.544606', 'BOM.532486', 'BOM.500333', 'BOM.500459', 'BOM.533274', 'BOM.540544', 'BOM.532810', 'BOM.523539', 'BOM.543527', 'BOM.539978', 'BOM.500338', 'BOM.544238', 'BOM.544597', 'BOM.530117', 'BOM.544367', 'BOM.539302', 'BOM.543635', 'BOM.533295', 'BOM.543981', 'BOM.506022', 'BOM.539883', 'BOM.532748', 'BOM.540724', 'BOM.532735', 'BOM.540293', 'BOM.532461', 'BOM.500126', 'BOM.542907', 'BOM.539150', 'BOM.532689', 'BOM.513519', 'BOM.531768', 'BOM.532898', 'BOM.532524', 'BOM.540173', 'BOM.542652', 'BOM.524051', 'BOM.522205']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.524000', 'BOM.539006', 'BOM.544606', 'BOM.532486', 'BOM.500333', 'BOM.500459', 'BOM.533274', 'BOM.540544', 'BOM.523539', 'BOM.532810', 'BOM.539978', 'BOM.543527', 'BOM.544238', 'BOM.500338', 'BOM.544597', 'BOM.530117', 'BOM.539302', 'BOM.544367', 'BOM.543635', 'BOM.533295', 'BOM.543981', 'BOM.506022', 'BOM.532748', 'BOM.539883', 'BOM.532735', 'BOM.540724', 'BOM.532461', 'BOM.540293', 'BOM.542907', 'BOM.500126', 'BOM.532689', 'BOM.539150', 'BOM.531768', 'BOM.513519', 'BOM.532524', 'BOM.532898', 'BOM.540173', 'BOM.542652', 'BOM.522205', 'BOM.524051']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532369', 'BOM.532805', 'BOM.534076', 'BOM.500325', 'BOM.543417', 'BOM.532884', 'BOM.533262', 'BOM.534597', 'BOM.532915', 'BOM.539450', 'BOM.543228', 'BOM.500355', 'BOM.543387', 'BOM.543265', 'BOM.535322', 'BOM.542333', 'BOM.544578', 'BOM.530517', 'BOM.544526', 'BOM.543248', 'BOM.541556', 'BOM.532939', 'BOM.540065', 'BOM.505509', 'BOM.517522', 'BOM.524230', 'BOM.542649', 'BOM.532955', 'BOM.543325', 'BOM.543957', 'BOM.532497', 'BOM.500330', 'BOM.543524', 'BOM.543213', 'BOM.532983', 'BOM.544240', 'BOM.532527', 'BOM.500339', 'BOM.520111', 'BOM.533122']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532369', 'BOM.532805', 'BOM.534076', 'BOM.500325', 'BOM.532884', 'BOM.543417', 'BOM.534597', 'BOM.533262', 'BOM.539450', 'BOM.532915', 'BOM.543228', 'BOM.500355', 'BOM.543265', 'BOM.543387', 'BOM.542333', 'BOM.535322', 'BOM.530517', 'BOM.544578', 'BOM.544526', 'BOM.543248', 'BOM.532939', 'BOM.541556', 'BOM.540065', 'BOM.505509', 'BOM.524230', 'BOM.517522', 'BOM.532955', 'BOM.542649', 'BOM.543325', 'BOM.543957', 'BOM.500330', 'BOM.532497', 'BOM.543213', 'BOM.543524', 'BOM.532983', 'BOM.544240', 'BOM.500339', 'BOM.532527', 'BOM.520111', 'BOM.533122']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.524667', 'BOM.541163', 'BOM.502090', 'BOM.532663', 'BOM.504614', 'BOM.514234', 'BOM.531201', 'BOM.535789', 'BOM.530073', 'BOM.540725', 'BOM.539199', 'BOM.540797', 'BOM.530549', 'BOM.544306', 'BOM.504918', 'BOM.523025', 'BOM.505790', 'BOM.534139', 'BOM.544282', 'BOM.543358', 'BOM.532163', 'BOM.500674', 'BOM.543989', 'BOM.501423', 'BOM.526807', 'BOM.540203', 'BOM.512329', 'BOM.540719', 'BOM.543959', 'BOM.535602', 'BOM.544250', 'BOM.531431', 'BOM.543066', 'BOM.522034', 'BOM.543936', 'BOM.517334', 'BOM.544533', 'BOM.538666', 'BOM.543984', 'BOM.543397']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.524667', 'BOM.541163', 'BOM.502090', 'BOM.532663', 'BOM.504614', 'BOM.514234', 'BOM.531201', 'BOM.535789', 'BOM.530073', 'BOM.540725', 'BOM.539199', 'BOM.540797', 'BOM.544306', 'BOM.530549', 'BOM.504918', 'BOM.523025', 'BOM.505790', 'BOM.534139', 'BOM.544282', 'BOM.543358', 'BOM.500674', 'BOM.532163', 'BOM.543989', 'BOM.501423', 'BOM.540203', 'BOM.526807', 'BOM.512329', 'BOM.540719', 'BOM.535602', 'BOM.543959', 'BOM.531431', 'BOM.544250', 'BOM.543066', 'BOM.522034', 'BOM.517334', 'BOM.543936', 'BOM.538666', 'BOM.544533', 'BOM.543397', 'BOM.543984']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532221', 'BOM.500285', 'BOM.543300', 'BOM.532670', 'BOM.500550', 'BOM.532218', 'BOM.540575', 'BOM.542760', 'BOM.500113', 'BOM.533206', 'BOM.543299', 'BOM.503806', 'BOM.500112', 'BOM.543412', 'BOM.532374', 'BOM.541540', 'BOM.513097', 'BOM.543686', 'BOM.543990', 'BOM.532029', 'BOM.544469', 'BOM.544572', 'BOM.532784', 'BOM.532725', 'BOM.544390', 'BOM.541967', 'BOM.540673', 'BOM.523598', 'BOM.544344', 'BOM.505192', 'BOM.511218', 'BOM.532638', 'BOM.544447', 'BOM.513262', 'BOM.532531', 'BOM.500387', 'BOM.544490', 'BOM.538562', 'BOM.503811', 'BOM.500472']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532221', 'BOM.500285', 'BOM.532670', 'BOM.543300', 'BOM.500550', 'BOM.532218', 'BOM.542760', 'BOM.540575', 'BOM.500113', 'BOM.533206', 'BOM.543299', 'BOM.503806', 'BOM.500112', 'BOM.543412', 'BOM.532374', 'BOM.541540', 'BOM.543686', 'BOM.513097', 'BOM.532029', 'BOM.543990', 'BOM.544469', 'BOM.544572', 'BOM.532784', 'BOM.532725', 'BOM.541967', 'BOM.544390', 'BOM.540673', 'BOM.523598', 'BOM.544344', 'BOM.505192', 'BOM.511218', 'BOM.532638', 'BOM.513262', 'BOM.544447', 'BOM.532531', 'BOM.500387', 'BOM.544490', 'BOM.538562', 'BOM.500472', 'BOM.503811']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.530239', 'BOM.532540', 'BOM.500407', 'BOM.509930', 'BOM.533553', 'BOM.544066', 'BOM.500405', 'BOM.543434', 'BOM.500403', 'BOM.519091', 'BOM.500800', 'BOM.500336', 'BOM.506854', 'BOM.512179', 'BOM.544285', 'BOM.500404', 'BOM.532509', 'BOM.532667', 'BOM.543596', 'BOM.506655', 'BOM.506222', 'BOM.500215', 'BOM.544619', 'BOM.542920', 'BOM.517168', 'BOM.500483', 'BOM.543573', 'BOM.517385', 'BOM.500408', 'BOM.524715', 'BOM.544574', 'BOM.532790', 'BOM.532390', 'BOM.532872', 'BOM.500770', 'BOM.526951', 'BOM.543249', 'BOM.532733', 'BOM.503310', 'BOM.539268']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.530239', 'BOM.532540', 'BOM.500407', 'BOM.509930', 'BOM.544066', 'BOM.533553', 'BOM.543434', 'BOM.500405', 'BOM.500403', 'BOM.519091', 'BOM.500336', 'BOM.500800', 'BOM.506854', 'BOM.512179', 'BOM.544285', 'BOM.500404', 'BOM.532667', 'BOM.532509', 'BOM.543596', 'BOM.506655', 'BOM.500215', 'BOM.506222', 'BOM.544619', 'BOM.542920', 'BOM.517168', 'BOM.500483', 'BOM.543573', 'BOM.517385', 'BOM.500408', 'BOM.524715', 'BOM.544574', 'BOM.532790', 'BOM.532390', 'BOM.532872', 'BOM.500770', 'BOM.526951', 'BOM.543249', 'BOM.532733', 'BOM.539268', 'BOM.503310']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.503100', 'BOM.522113', 'BOM.539871', 'BOM.540212', 'BOM.540769', 'BOM.543321', 'BOM.532856', 'BOM.532928', 'BOM.532755', 'BOM.533326', 'BOM.500850', 'BOM.532371', 'BOM.539658', 'BOM.544174', 'BOM.532966', 'BOM.500413', 'BOM.500114', 'BOM.532375', 'BOM.500470', 'BOM.544612', 'BOM.532349', 'BOM.543413', 'BOM.500412', 'BOM.500400', 'BOM.500260', 'BOM.532779', 'BOM.540595', 'BOM.500420', 'BOM.533158', 'BOM.500414', 'BOM.542460', 'BOM.500411', 'BOM.542141', 'BOM.544028', 'BOM.500570', 'BOM.501301', 'BOM.507205', 'BOM.544569', 'BOM.532804', 'BOM.501425']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.503100', 'BOM.522113', 'BOM.540212', 'BOM.539871', 'BOM.540769', 'BOM.543321', 'BOM.532856', 'BOM.532928', 'BOM.533326', 'BOM.532755', 'BOM.532371', 'BOM.500850', 'BOM.539658', 'BOM.544174', 'BOM.532966', 'BOM.500413', 'BOM.500114', 'BOM.532375', 'BOM.544612', 'BOM.500470', 'BOM.543413', 'BOM.532349', 'BOM.500400', 'BOM.500412', 'BOM.500260', 'BOM.532779', 'BOM.540595', 'BOM.500420', 'BOM.533158', 'BOM.500414', 'BOM.500411', 'BOM.542460', 'BOM.544028', 'BOM.542141', 'BOM.501301', 'BOM.500570', 'BOM.544569', 'BOM.507205', 'BOM.501425', 'BOM.532804']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532953', 'BOM.540762', 'BOM.532478', 'BOM.544824', 'BOM.534976', 'BOM.543942', 'BOM.532477', 'BOM.506690', 'BOM.543689', 'BOM.532867', 'BOM.517146', 'BOM.532432', 'BOM.532343', 'BOM.534392', 'BOM.544443', 'BOM.512070', 'BOM.543965', 'BOM.543238', 'BOM.533655', 'BOM.507880', 'BOM.542904', 'BOM.519156', 'BOM.544515', 'BOM.517506', 'BOM.521064', 'BOM.532538', 'BOM.544322', 'BOM.511742', 'BOM.532505', 'BOM.500251', 'BOM.531266', 'BOM.532356', 'BOM.544317', 'BOM.532539', 'BOM.502986', 'BOM.520056', 'BOM.500148', 'BOM.533269', 'BOM.532156', 'BOM.509243']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.540762', 'BOM.532953', 'BOM.544824', 'BOM.532478', 'BOM.534976', 'BOM.543942', 'BOM.532477', 'BOM.506690', 'BOM.532867', 'BOM.543689', 'BOM.517146', 'BOM.532432', 'BOM.534392', 'BOM.532343', 'BOM.512070', 'BOM.544443', 'BOM.543965', 'BOM.543238', 'BOM.533655', 'BOM.507880', 'BOM.542904', 'BOM.519156', 'BOM.517506', 'BOM.544515', 'BOM.521064', 'BOM.532538', 'BOM.511742', 'BOM.544322', 'BOM.532505', 'BOM.500251', 'BOM.532356', 'BOM.531266', 'BOM.544317', 'BOM.532539', 'BOM.520056', 'BOM.502986', 'BOM.533269', 'BOM.500148', 'BOM.532156', 'BOM.509243']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.500238', 'BOM.532300', 'BOM.507685', 'BOM.543985', 'BOM.544321', 'BOM.532822', 'BOM.505872', 'BOM.532144', 'BOM.539118', 'BOM.517498', 'BOM.543528', 'BOM.533339', 'BOM.532648', 'BOM.543463', 'BOM.524200', 'BOM.544642', 'BOM.505533', 'BOM.543950', 'BOM.516072', 'BOM.544488', 'BOM.541578', 'BOM.543992', 'BOM.505537', 'BOM.540180', 'BOM.520113', 'BOM.500444', 'BOM.538268', 'BOM.534618', 'BOM.544307', 'BOM.532553', 'BOM.514162', 'BOM.500575', 'BOM.544277', 'BOM.523261', 'BOM.532757', 'BOM.543350', 'BOM.504067', 'BOM.544570', 'BOM.509966', 'BOM.512529']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
40 Failed downloads:
ERROR:yfinance:['BOM.532300', 'BOM.500238', 'BOM.507685', 'BOM.543985', 'BOM.532822', 'BOM.544321', 'BOM.505872', 'BOM.532144', 'BOM.517498', 'BOM.539118', 'BOM.533339', 'BOM.543528', 'BOM.532648', 'BOM.543463', 'BOM.524200', 'BOM.544642', 'BOM.543950', 'BOM.505533', 'BOM.516072', 'BOM.544488', 'BOM.541578', 'BOM.543992', 'BOM.505537', 'BOM.540180', 'BOM.500444', 'BOM.520113', 'BOM.538268', 'BOM.534618', 'BOM.544307', 'BOM.532553', 'BOM.500575', 'BOM.514162', 'BOM.523261', 'BOM.544277', 'BOM.543350', 'BOM.532757', 'BOM.544570', 'BOM.504067', 'BOM.512529', 'BOM.509966']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

ERROR:yfinance:
3 Failed downloads:
ERROR:yfinance:['BOM.533023', 'BOM.532321', 'BOM.531335']: YFPricesMissingError('possibly delisted; no price data found  (period=2y) (Yahoo error = "No data found, symbol may be delisted")')
ERROR:yfinance:
3 Failed downloads:
ERROR:yfinance:['BOM.532321', 'BOM.533023', 'BOM.531335']: YFPricesMissingError('possibly delisted; no price data found  (period=5y) (Yahoo error = "No data found, symbol may be delisted")')

Nifty 500 done
Done in ~40 min
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

✅ Saved daily_hits.csv → /content/drive/MyDrive/Stockbee/daily_hits.csv  (2174 rows)
   Scans: 11  |  Tickers: 1535

In [ ]:
# CELL 9 — Print summary
from datetime import datetime
LABELS={"bearish_momentum":"Bearish Momentum","vcp_setup":"VCP Setup",
    "satish_bullish":"Satish Bullish","hardik":"Hardik Scan",
    "nr6":"NR6 Narrowest Range","rocket_base":"Rocket Base",
    "ep_breakout":"EP Breakout","high_20d":"20-Day High (US)",
    "high_2month":"2-Month High (US)","gapup_3pct":"Gap Up 3pct","up_4pct":"Up 4pct"}
print("\n"+"="*65)
print(f"  DAILY RESULTS  {datetime.now().strftime('%d %b %Y  %H:%M')}")
print("="*65)
for k,label in LABELS.items():
    sp=sp500_hits.get(k,[]); r2k=r2000_hits.get(k,[]); nif=nifty_hits.get(k,[])
    tot=len(sp)+len(r2k)+len(nif)
    if tot==0: continue
    print(f"  {label:<38} S&P:{len(sp):>3} R2K:{len(r2k):>3} Nifty:{len(nif):>3} Total:{tot:>4}")
    if sp:  print(f"    S&P:   {chr(32).join(sp[:15])}")
    if r2k: print(f"    R2K:   {chr(32).join(r2k[:15])}")
    if nif: print(f"    Nifty: {chr(32).join(nif[:15])}")
print("="*65)

=================================================================
  DAILY RESULTS  13 Aug 2026  13:33
=================================================================
  Bearish Momentum                       S&P: 26 R2K: 24 Nifty: 12 Total:  62
    S&P:   AFL MO AIG AAPL APP ACGL AVB CDNS CTVA CRH DDOG DECK EBAY EQR LII
    R2K:   ACM AXS AZN BTI BUD CRC CRS DKS ELS GSK HLI JBTM LMND MSM NVS
    Nifty: ABLBL.NS BIOCON.NS CIEINDIA.NS CEMPRO.NS CUB.NS JKTYRE.NS LATENTVIEW.NS NLCINDIA.NS PWL.NS SBILIFE.NS SHYAMMETL.NS SYNGENE.NS
  VCP Setup                              S&P:255 R2K:361 Nifty:181 Total: 797
    S&P:   MMM ABT ABBV A APD ABNB ALLE ALL AMZN AMCR AXP AWK AMP AME AMGN
    R2K:   AAMI ABCB ACA AEG AEM AER AFG AGL AHR AIR AIT ALSN AM AMBQ AMC
    Nifty: ABB.NS ACMESOLAR.NS APLAPOLLO.NS AUBANK.NS AARTIIND.NS ACE.NS ABCAPITAL.NS CPPLUS.NS AEGISLOG.NS AEGISVOPAK.NS AFFLE.NS AJANTPHARM.NS ANANDRATHI.NS ANANTRAJ.NS ANTHEM.NS
  Satish Bullish                         S&P:  2 R2K:  5 Nifty:  3 Total:  10
    S&P:   CSCO DELL
    R2K:   BMO CACI EAT RY VIK
    Nifty: ETERNAL.NS HSCL.NS TMPV.NS
  Hardik Scan                            S&P: 10 R2K:  2 Nifty:  3 Total:  15
    S&P:   CF FDX GD HUM INCY IBKR JNJ LLY LMT TRGP
    R2K:   LNG MOH
    Nifty: HCLTECH.NS KALYANKJIL.NS LODHA.NS
  NR6 Narrowest Range                    S&P: 99 R2K:394 Nifty:107 Total: 600
    S&P:   AMD A ARE MO AEE AEP AIG AMGN APA AMAT ADM T BG CHRW CASY
    R2K:   AAMI AAT AAUC ACEL ACR ACV AD AEG AFGB AGCO AGL AGM AHR AIN AIO
    Nifty: ACE.NS ABFRL.NS ABLBL.NS AFCONS.NS ALKEM.NS ANGELONE.NS APTUS.NS ASTERDM.NS AXISBANK.NS BEML.NS BSE.NS BAJFINANCE.NS BAJAJHLDNG.NS BAJAJHFL.NS BANDHANBNK.NS
  Rocket Base                            S&P:109 R2K:230 Nifty:102 Total: 441
    S&P:   ACN AMD A ABNB AMZN AMP APH APO AMAT ARES ANET AIZ ADP AXON BAC
    R2K:   AAMI ACA AGL AGM AIR AIT ALK AMBQ AMG AMN ANDG ARMK ARW ASH ASX
    Nifty: ACMESOLAR.NS AARTIIND.NS ACUTAAS.NS ADANIENSOL.NS ADANIENT.NS ADANIGREEN.NS CPPLUS.NS AEGISLOG.NS AEGISVOPAK.NS AJANTPHARM.NS ABDL.NS ANANDRATHI.NS ANANTRAJ.NS APARINDS.NS ATHERENERG.NS
  EP Breakout                            S&P:  2 R2K: 14 Nifty:  1 Total:  17
    S&P:   ANET CRL
    R2K:   AII DAO DCO EAT GKOS HAE HRB MLR MSGE RMAX RSKD SMWB USFD WHD
    Nifty: SOLARINDS.NS
  20-Day High (US)                       S&P:  0 R2K: 25 Nifty:  0 Total:  25
    R2K:   ALUB AVEX BEBE BIII BTX BWIV CICC COPL IHD INFQ JENA KPET MICC MLR MMT
  2-Month High (US)                      S&P:  0 R2K: 12 Nifty:  0 Total:  12
    R2K:   ALUB BEBE BIII BWIV COPL MICC MLR NL PAII SOUL WENC YCY
  Gap Up 3pct                            S&P: 28 R2K: 87 Nifty:  3 Total: 118
    S&P:   AMAT ANET CIEN COHR FIX GLW DELL ETN FLEX GEV GNRC INTC KLAC LRCX LITE
    R2K:   AG AGX AII AMBQ AMPX AMRC ATI AU AVAL BE BKSY BLND CAVA CLS CRD
    Nifty: CPPLUS.NS LENSKART.NS SUNTV.NS
  Up 4pct                                S&P: 10 R2K: 58 Nifty:  9 Total:  77
    S&P:   AKAM CBOE CNC CIEN DRI DELL HPE HUM MRNA SMCI
    R2K:   ACVA AKA ALIT AMC ARX BALY BETA BORR CANG CINT CLPR CLS CON CRD CVI
    Nifty: ASTRAL.NS BHARTIHEXA.NS CYIENT.NS GPIL.NS IFCI.NS NETWEB.NS POONAWALLA.NS SARDAEN.NS SOLARINDS.NS
=================================================================

---
## Stockbee US Screener
Runs after daily scans. Results added to the same Google Sheet.

In [ ]:
# Stockbee: Install & Imports
# Most packages already installed above. Just ensure tqdm is present.
import subprocess, sys
subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-q', 'tqdm'])

import warnings, os, gc, time
from datetime import datetime
from typing import Optional
from concurrent.futures import ThreadPoolExecutor, as_completed

import numpy as np
import pandas as pd
import requests
import yfinance as yf
from tqdm.notebook import tqdm

warnings.filterwarnings('ignore')
print('✅ Stockbee imports ready')

✅ Stockbee imports ready

In [ ]:
# Stockbee: Configuration
# Aligned to Pine Script v2 — DAMA removed, 9M Vol / +4% / -4% updated

# ── Universe pre-filters ──
MIN_PRICE           = 10.0   # close >= $10
MIN_AVG_VOL_50K     = 100    # 50d avg vol >= 100K (scans 1/2/3)
MIN_AVG_VOL_200K    = 200    # 50d avg vol >= 200K (scan 4)

# ── EP Scan thresholds ──
EXTREME_SALES_PCT   = 99     # Scan 1: revenue YoY >= 99%
SALES_GROWTH_PCT    = 39     # Scan 2/3: revenue YoY >= 39% (last Q AND 2Q avg)
MIN_ANNUAL_SALES_M  = 25     # trailing 4Q revenue >= $25M
EPS_GROWTH_PCT      = 39     # Scan 4: EPS YoY >= 39% (BOTH quarters required)
SALES_GROWTH_EP4    = 20     # Scan 4: revenue YoY >= 20%
MKTCAP_SCAN3_B      = 11     # Scan 3: mkt cap <= $11B (USD only)
IPO_YEARS_SCAN3     = 10     # Scan 3: IPO within 10 years

# ── Entry MA & ATR (DAMA removed in Pine v2) ──
ENTRY_MA_PERIOD     = 70     # MA70 for ATR entry threshold
ATR_MULTIPLE        = 2.0    # price >= MA + N*ATR to be in entry zone
USE_DI_FILTER       = True   # require +DI > -DI (price > MA proxy)

# ── Pattern filter toggles ──
USE_TTT_FILTER      = False
USE_MWG_FILTER      = False
USE_BMS_FILTER      = False

# ── Momentum flags (Pine v2 updated definitions) ──
TI65_BULL           = 1.05   # avgC7 / avgC65 >= 1.05
VOL_9M              = 9_000_000  # 9M Vol: also needs vol>prior AND close up 4%+
PLUS4PCT            = 4.0    # threshold for BO and BD flags

# ── Gap detection (TTT & MWG shared) ──
GAP_JUMP_MULT       = 1.20
GAP_RANGE_PCT       = 0.04
GAP_LOOKBACK        = 100

# ── Performance ──
SB_MAX_WORKERS      = 8      # parallel threads
SB_BATCH_SIZE       = 50     # checkpoint every N tickers
SB_HISTORY          = '18mo'

# ── Output files ──
RESULTS_FILE        = 'stockbee_results.csv'
HITS_FILE           = 'stockbee_hits.csv'

print('✅ Stockbee config loaded (Pine v2 aligned)')

✅ Stockbee config loaded (Pine v2 aligned)

In [ ]:
# Stockbee: Universe Builder

def fetch_us_tickers():
    SKIP_SUFFIXES = ('W', 'R', 'U', 'Z', 'L')
    KNOWN_ETFS    = {'SPY','QQQ','IWM','DIA','GLD','SLV','TLT','HYG','LQD',
                     'XLB','XLC','XLE','XLF','XLI','XLK','XLP','XLU','XLV','XLY'}
    url = ('https://raw.githubusercontent.com/'
           'rreichel3/US-Stock-Symbols/main/all/all_tickers.txt')
    try:
        resp = requests.get(url, timeout=15)
        resp.raise_for_status()
        raw = [t.strip() for t in resp.text.split('\n') if t.strip()]
    except Exception as e:
        print(f'⚠️  Ticker list failed ({e}). Using fallback.')
        return _sb_fallback_tickers()
    clean = []
    for t in raw:
        if len(t) > 5:                          continue
        if '.' in t or '-' in t:               continue
        if t in KNOWN_ETFS:                     continue
        if t.endswith(SKIP_SUFFIXES) and len(t) > 3: continue
        clean.append(t)
    print(f'✅ Stockbee universe: {len(clean):,} US tickers')
    return clean

def _sb_fallback_tickers():
    return [
        'AAPL','MSFT','NVDA','TSLA','AMZN','META','GOOGL','AMD','AVGO','NFLX',
        'SMCI','PLTR','MSTR','IONQ','CRWD','SNOW','DDOG','ZS','MDB','BILL',
        'AFRM','UPST','SOFI','HOOD','RBLX','COIN','PATH','AI','GTLB','SOUN',
        'JOBY','ACHR','RKLB','ASTS','LUNR','RDDT','CELH','ELF','HIMS','IMVT',
        'AXSM','INSM','CAVA','BROS','WING','CMG','SHAK','SBUX','SHOP','MELI',
        'REGN','BIIB','VRTX','ALNY','MRNA','BNTX','GILD','AMGN','ABBV','LLY',
        'JPM','BAC','WFC','GS','MARA','RIOT','CLSK','WULF','IREN','COST',
    ]

ALL_TICKERS = fetch_us_tickers()
print(f'   Ready to scan {len(ALL_TICKERS):,} tickers')

✅ Stockbee universe: 5,645 US tickers
   Ready to scan 5,645 tickers

In [ ]:
from typing import Optional
# Stockbee: Core Calculation Engine — Pine Script v2 aligned

# ── Revenue YoY: Pine requires prior > 0 (positive base only) ──
def sb_safe_pct_rev(new_val, old_val):
    if pd.isna(new_val) or pd.isna(old_val) or old_val <= 0: return None
    return ((new_val - old_val) / old_val) * 100

# ── EPS YoY: Pine uses abs(prior) as denominator ──
def sb_safe_pct_eps(new_val, old_val):
    if pd.isna(new_val) or pd.isna(old_val) or old_val == 0: return None
    return ((new_val - old_val) / abs(old_val)) * 100

def sb_calc_atr(high, low, close, period=14):
    tr = pd.concat([
        high - low,
        (high - close.shift(1)).abs(),
        (low  - close.shift(1)).abs(),
    ], axis=1).max(axis=1)
    return tr.ewm(alpha=1/period, adjust=False).mean()

def sb_count_gaps(close, high, low, lookback=100):
    """
    Gap bar: close > 1.2*prior AND (high-low) < 0.04*close
    Pine v2 fix: requires prior close is not NaN (not na(close[1]) guard)
    """
    prior = close.shift(1)
    is_gap = (
        prior.notna() &
        (close > GAP_JUMP_MULT * prior) &
        ((high - low) < GAP_RANGE_PCT * close)
    ).astype(int)
    return is_gap.rolling(lookback, min_periods=lookback).sum()

def sb_get_fundamentals(tk):
    out = dict(rev_q=[], eps_q=[], annual_sales_m=None,
               market_cap=None, currency=None, ipo_years_ago=None)
    try:
        fi = tk.fast_info
        out['market_cap'] = getattr(fi, 'market_cap', None)
        out['currency']   = getattr(fi, 'currency', None)
    except Exception: pass
    try:
        fins = tk.quarterly_financials
        if fins is not None and not fins.empty:
            for label in ['Total Revenue', 'TotalRevenue', 'Revenue']:
                if label in fins.index:
                    row = fins.loc[label].sort_index(ascending=False)
                    out['rev_q'] = [v for v in row.values if not pd.isna(v)]
                    break
    except Exception: pass
    try:
        eps_df = tk.quarterly_earnings
        if eps_df is not None and not eps_df.empty and 'Reported EPS' in eps_df.columns:
            eps_s = eps_df.sort_index(ascending=False)['Reported EPS']
            out['eps_q'] = [v for v in eps_s.values if not pd.isna(v)]
    except Exception: pass
    if len(out['rev_q']) >= 4:
        out['annual_sales_m'] = sum(out['rev_q'][:4]) / 1_000_000
    try:
        info = tk.info
        raw  = info.get('firstTradeDateEpochUtc') or info.get('ipoExpectedDate')
        if raw:
            dt = datetime.fromtimestamp(raw) if isinstance(raw, (int,float)) else pd.to_datetime(raw)
            out['ipo_years_ago'] = (datetime.now() - dt).days / 365.25
    except Exception: pass
    return out

# ── Pattern filters ──
def sb_calc_ttt(close, high, low, volume,
                min_vol=300_000, min_price=10.0, max_3bar=1.5, max_today=0.3, lookback=100):
    """Ants TTT: tight consolidation, no gaps, volume (fail-closed)."""
    vol_ok    = volume.shift(1).rolling(3).min() >= min_vol
    price_ok  = close > min_price
    pct_3bar  = ((close - close.shift(3)) / close.shift(3) * 100).abs()
    consol_ok = pct_3bar <= max_3bar
    pct_today = ((close - close.shift(1)) / close.shift(1) * 100).abs()
    tight_ok  = pct_today <= max_today
    no_gaps   = sb_count_gaps(close, high, low, lookback) == 0
    return (vol_ok & price_ok & consol_ok & tight_ok & no_gaps).fillna(False)

def sb_calc_mwg(close, high, low, volume,
                min_vol=100_000, vol_days=3, min_price=10.0, max_day=0.4, lookback=100):
    """Ants Bullish/MWG: momentum without gaps (fail-closed)."""
    low30      = close.rolling(30).min()
    avg7       = close.rolling(7).mean()
    avg65      = close.rolling(65).mean()
    mom_ok     = (close / low30 >= 1.20) | (avg7 / avg65 >= 1.05)
    price_ok   = close > min_price
    ctrl_ok    = ((close - close.shift(1)) / close.shift(1) * 100).abs() <= max_day
    vol_ok     = volume.shift(1).rolling(vol_days).min() >= min_vol
    no_gaps    = sb_count_gaps(close, high, low, lookback) == 0
    return (mom_ok & price_ok & ctrl_ok & vol_ok & no_gaps).fillna(False)

def sb_calc_bms(close, high, low, volume, open_,
                min_price=10.0, min_vol_c1=1_000_000, min_vol_c2=100_000,
                breakout_pct=4.0, stability_pct=2.0, close_str_min=0.70):
    """Bullish Combo: candle pattern + volume. Pine v2 fix: open>0 guard."""
    candle   = ((close - open_) / open_.clip(lower=0.01)) >= 0.02
    today_r  = high - low
    stability = ((close.shift(1) / close.shift(2)) - 1).abs() <= (stability_pct / 100)
    cond1    = candle & (volume > min_vol_c1) & (today_r >= (high.shift(1)-low.shift(1)).abs()) & stability
    cond2    = ((close / close.shift(1)) >= (1 + breakout_pct/100)) & (volume > volume.shift(1)) & (volume >= min_vol_c2) & stability
    price_ok = close >= min_price
    cs_ok    = ((close - low) / (high - low).clip(lower=1e-9)) >= close_str_min
    return ((cond1 | cond2) & price_ok & cs_ok).fillna(False)


# ── Main single-ticker screener ──
def sb_screen_one(sym):
    row = dict(
        ticker=sym, price=None,
        scan1=False, scan2=False, scan3=False, scan4=False, momentum=False,
        ttt_pass=False, mwg_pass=False, bms_pass=False, di_bullish=False,
        flag_ti65=False,
        flag_9mvol=False,        # 9M vol + vol>prior + close up 4%+ (Pine v2)
        flag_plus4_bo=False,     # +4% breakout: pct>=4 AND vol>prior (Pine v2)
        flag_minus4_bd=False,    # -4% breakdown: pct<=-4 AND vol>prior (NEW Pine v2)
        ti65=None, sales_pct=None, eps_pct=None,
        annual_sales_m=None, mktcap_b=None, avg_vol_50k=None,
        adr_pct=None, ext_atr=None, error=None,
    )
    try:
        tk   = yf.Ticker(sym)
        hist = tk.history(period=SB_HISTORY, interval='1d', auto_adjust=True)
        if hist.empty or len(hist) < 70:
            row['error'] = 'no_data'; return row

        close  = hist['Close']
        high   = hist['High']
        low    = hist['Low']
        volume = hist['Volume']
        open_  = hist['Open']

        last_c  = float(close.iloc[-1])
        last_v  = float(volume.iloc[-1])
        avg50k  = float(volume.rolling(50).mean().iloc[-1]) / 1000

        if last_c < MIN_PRICE or avg50k < MIN_AVG_VOL_50K:
            row['error'] = 'filtered'; return row

        row['price']       = round(last_c, 2)
        row['avg_vol_50k'] = round(avg50k, 1)

        atr14 = sb_calc_atr(high, low, close, 14)
        latr  = float(atr14.iloc[-1])
        ema   = close.rolling(ENTRY_MA_PERIOD).mean()
        lma   = float(ema.iloc[-1])

        # ATR entry zone (DAMA removed in Pine v2)
        in_entry_zone = last_c >= lma + ATR_MULTIPLE * latr

        # ADR%
        row['adr_pct'] = round(float(((high-low)/close*100).rolling(14).mean().iloc[-1]), 2)

        # Extension from MA70 in ATR units
        ma70 = close.rolling(70).mean()
        row['ext_atr'] = round((last_c - float(ma70.iloc[-1])) / latr, 2) if latr > 0 else None

        # TI65: avgC7 / avgC65
        avg7   = close.rolling(7).mean()
        avg65  = close.rolling(65).mean()
        lti65  = float((avg7 / avg65).iloc[-1]) if not pd.isna((avg7/avg65).iloc[-1]) else 0
        row['ti65']      = round(lti65, 3)
        row['flag_ti65'] = lti65 >= TI65_BULL

        # DI proxy: price above MA
        row['di_bullish'] = last_c > lma

        # Prior day values
        prior_c = float(close.iloc[-2])  if len(close)  >= 2 else last_c
        prior_v = float(volume.iloc[-2]) if len(volume) >= 2 else last_v
        pct_today = ((last_c - prior_c) / prior_c * 100) if prior_c else 0

        # 9M Vol flag — Pine v2: vol>=9M AND vol>prior AND close>=1.04*prior
        row['flag_9mvol'] = (last_v >= VOL_9M and last_v > prior_v
                             and last_c >= 1.04 * prior_c)

        # +4% Breakout — Pine v2: pct>=4 AND vol>prior
        row['flag_plus4_bo']  = pct_today >= PLUS4PCT and last_v > prior_v

        # -4% Breakdown — NEW Pine v2: pct<=-4 AND vol>prior
        row['flag_minus4_bd'] = pct_today <= -PLUS4PCT and last_v > prior_v

        # Pattern filters
        row['ttt_pass'] = bool(sb_calc_ttt(close, high, low, volume).iloc[-1])
        row['mwg_pass'] = bool(sb_calc_mwg(close, high, low, volume).iloc[-1])
        row['bms_pass'] = bool(sb_calc_bms(close, high, low, volume, open_).iloc[-1])

        passes_di  = row['di_bullish'] if USE_DI_FILTER  else True
        passes_ttt = row['ttt_pass']   if USE_TTT_FILTER else True
        passes_mwg = row['mwg_pass']   if USE_MWG_FILTER else True
        passes_bms = row['bms_pass']   if USE_BMS_FILTER else True

        # Momentum = ATR entry zone + optional filters (DAMA removed)
        row['momentum'] = in_entry_zone and passes_di and passes_ttt and passes_mwg and passes_bms

        # Fundamentals
        fin  = sb_get_fundamentals(tk)
        revq = fin['rev_q']
        epsq = fin['eps_q']
        ann  = fin['annual_sales_m']
        mcap = fin['market_cap']
        curr = fin['currency']
        ipo  = fin['ipo_years_ago']

        row['annual_sales_m'] = round(ann, 1)       if ann  else None
        row['mktcap_b']       = round(mcap/1e9, 2)  if mcap else None

        # Revenue YoY — Pine: prior > 0 (fail-closed)
        sg  = sb_safe_pct_rev(revq[0], revq[4]) if len(revq) >= 5 else None
        sg1 = sb_safe_pct_rev(revq[1], revq[5]) if len(revq) >= 6 else None
        # avgSalesChg2Q: FAIL-CLOSED — both quarters required (Pine v2 change)
        sg2 = (sg + sg1) / 2 if (sg is not None and sg1 is not None) else None
        row['sales_pct'] = round(sg, 1) if sg is not None else None

        # EPS YoY — Pine: abs(prior) denominator
        eg  = sb_safe_pct_eps(epsq[0], epsq[4]) if len(epsq) >= 5 else None
        eg1 = sb_safe_pct_eps(epsq[1], epsq[5]) if len(epsq) >= 6 else None
        row['eps_pct'] = round(eg, 1) if eg is not None else None

        price_ok  = last_c  >= MIN_PRICE
        vol100_ok = avg50k  >= MIN_AVG_VOL_50K
        vol200_ok = avg50k  >= MIN_AVG_VOL_200K
        sales_ok  = ann is not None and ann >= MIN_ANNUAL_SALES_M

        # Scan 1: Extreme Sales (99%+ YoY)
        row['scan1'] = (sg is not None and sg >= EXTREME_SALES_PCT
                        and sales_ok and price_ok and vol100_ok)

        # Scan 2: Sales Growth 39/39 — fail-closed 2Q avg
        sales_core = (sg  is not None and sg  >= SALES_GROWTH_PCT
                      and sg2 is not None and sg2 >= SALES_GROWTH_PCT
                      and sales_ok and price_ok and vol100_ok)
        row['scan2'] = sales_core

        # Scan 3: Growth/Turnaround — USD currency check (Pine v2)
        usd_ok    = (curr == 'USD' or curr is None)
        small_mid = (mcap is not None and mcap <= MKTCAP_SCAN3_B * 1e9 and usd_ok)
        new_ipo   = (ipo is None or ipo <= IPO_YEARS_SCAN3)
        row['scan3'] = sales_core and small_mid and new_ipo

        # Scan 4: EPS + Sales — BOTH eps quarters required (Pine v2)
        sg2_ep4 = (sg + sg1) / 2 if (sg is not None and sg1 is not None) else None
        row['scan4'] = (eg  is not None and eg  >= EPS_GROWTH_PCT
                        and eg1 is not None and eg1 >= EPS_GROWTH_PCT
                        and sg  is not None and sg  >= SALES_GROWTH_EP4
                        and sg2_ep4 is not None and sg2_ep4 >= SALES_GROWTH_EP4
                        and sales_ok and price_ok and vol200_ok)

    except Exception as exc:
        row['error'] = str(exc)[:60]
    return row

print('✅ Stockbee calculation engine ready (Pine v2 aligned)')

✅ Stockbee calculation engine ready (Pine v2 aligned)

In [ ]:
import gc
# Stockbee: Main Scan Runner

def sb_save_checkpoint(results, cp_path, hits_path):
    try:
        df_cp = pd.DataFrame(results)
        scan_cols = [c for c in ['scan1','scan2','scan3','scan4','momentum'] if c in df_cp]
        df_cp['any_hit'] = df_cp[scan_cols].any(axis=1)
        df_cp.to_csv(cp_path, index=False)
        df_cp[df_cp['any_hit']].to_csv(hits_path, index=False)
    except Exception: pass


def run_stockbee_scan(tickers, save_dir='.'):
    cp_path      = os.path.join(save_dir, 'sb_checkpoint.csv')
    hits_path    = os.path.join(save_dir, HITS_FILE)
    results_path = os.path.join(save_dir, RESULTS_FILE)

    # Resume from checkpoint
    results, done = [], set()
    if os.path.exists(cp_path):
        try:
            prev = pd.read_csv(cp_path)
            results = prev.to_dict('records')
            done    = set(prev['ticker'].tolist())
            print(f'♻️  Resuming: {len(done)} already done')
        except Exception: pass

    remaining  = [t for t in tickers if t not in done]
    start_time = time.time()
    print(f'\n{"━"*60}')
    print(f'  STOCKBEE SCAN  |  {datetime.now().strftime("%Y-%m-%d %H:%M")}')
    print(f'  {len(remaining):,} tickers  |  {SB_MAX_WORKERS} threads')
    print(f'{"━"*60}\n')

    with ThreadPoolExecutor(max_workers=SB_MAX_WORKERS) as pool:
        futures = {pool.submit(sb_screen_one, sym): sym for sym in remaining}
        with tqdm(total=len(remaining), unit='ticker',
                  bar_format='{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}]') as pbar:
            for i, future in enumerate(as_completed(futures), 1):
                sym = futures[future]
                try:
                    row = future.result(timeout=30)
                except Exception as e:
                    row = {k: False for k in ['scan1','scan2','scan3','scan4','momentum',
                           'flag_ti65','flag_9mvol','flag_plus4_bo','flag_minus4_bd']}
                    row.update(ticker=sym, error=str(e)[:40])
                results.append(row)
                pbar.set_postfix({'last': sym}, refresh=False)
                pbar.update(1)
                if i % SB_BATCH_SIZE == 0:
                    sb_save_checkpoint(results, cp_path, hits_path)
                    elapsed = time.time() - start_time
                    eta_s   = (len(remaining) - i) / (i / elapsed) if elapsed else 0
                    pbar.set_postfix({'ETA': f'{int(eta_s//60)}m{int(eta_s%60)}s'})
                gc.collect()

    df = pd.DataFrame(results)
    df['any_hit'] = df[['scan1','scan2','scan3','scan4','momentum']].any(axis=1)
    df.to_csv(results_path, index=False)
    df[df['any_hit']].to_csv(hits_path, index=False)

    elapsed = time.time() - start_time
    print(f'\n{"━"*60}')
    print(f'  ✅ DONE  |  {elapsed/60:.1f} min  |  {int(df["any_hit"].sum())} hits')
    print(f'{"━"*60}\n')
    return df

print('✅ Stockbee runner ready')

✅ Stockbee runner ready

In [ ]:
# Stockbee: Results Display

def sb_display_results(df):
    scan_defs = [
        ('scan1',    'SCAN 1',   'Extreme Sales Growth (99%+ YoY)'),
        ('scan2',    'SCAN 2',   'Sales Growth (39%/39% fail-closed 2Q)'),
        ('scan3',    'SCAN 3',   'Growth/Turnaround (<=11B USD, IPO <10y)'),
        ('scan4',    'SCAN 4',   'Earnings + Sales (39%E both Q / 20%S)'),
        ('momentum', 'MOMENTUM', 'ATR Entry Zone (MA70 + 2xATR + DI)'),
    ]
    cols = ['ticker','price','sales_pct','eps_pct','annual_sales_m',
            'mktcap_b','avg_vol_50k','ti65','adr_pct','ext_atr']

    total = int(df['any_hit'].sum()) if 'any_hit' in df.columns else 0
    print(f'\n{"="*80}')
    print(f'  STOCKBEE RESULTS  |  {datetime.now().strftime("%Y-%m-%d %H:%M")}')
    print(f'  Universe: {len(df):,}  |  Hits: {total}')
    print(f'{"="*80}')

    for key, tag, label in scan_defs:
        if key not in df.columns: continue
        subset = df[df[key]].copy()
        if subset.empty:
            print(f'\n  [{tag}] {label}  →  No hits'); continue
        subset = subset.sort_values('sales_pct', ascending=False, na_position='last')
        subset['flags'] = (
            subset['flag_9mvol'].apply(lambda x: '🔊' if x else '') +
            subset['flag_plus4_bo'].apply(lambda x: '🚀' if x else '') +
            subset['flag_minus4_bd'].apply(lambda x: '🔻' if x else '') +
            subset['flag_ti65'].apply(lambda x: '📈' if x else '')
        )
        print(f'\n  ▌ [{tag}] {label}  ({len(subset)} stocks)')
        display_cols = [c for c in cols if c in subset.columns] + ['flags']
        try:
            from IPython.display import display as ipy_display
            ipy_display(subset[display_cols].reset_index(drop=True))
        except ImportError:
            print(subset[display_cols].to_string(index=False))

    print(f'\n  Flags: 🔊 9M+vol+4%up  🚀 +4% BO  🔻 -4% BD  📈 TI65 bullish\n')


def sb_top_momentum(df, n=20):
    """Top N stocks in ATR entry zone ranked by TI65."""
    if 'momentum' not in df.columns: return df.head(0)
    mom = df[df['momentum']].copy()
    mom['score'] = mom['ti65'].fillna(0)
    return mom.sort_values('score', ascending=False).head(n)

print('✅ Stockbee display functions ready')

✅ Stockbee display functions ready

In [ ]:
# Stockbee: ENTRY POINT
# @title ▶️ Run Stockbee Scan
# ⏱️ ~45-90 min for full universe. Checkpoint auto-saves every 50 tickers.

if True:
    save_dir = '.'

    # Run scan
    df = run_stockbee_scan(ALL_TICKERS, save_dir=save_dir)

    # Display results
    df['any_hit'] = df[['scan1','scan2','scan3','scan4','momentum']].any(axis=1)
    sb_display_results(df)

    # Top momentum
    print('\n  🏆 TOP 20 MOMENTUM STOCKS (ATR Entry Zone, ranked by TI65)\n')
    top = sb_top_momentum(df, 20)
    try:
        from IPython.display import display as ipy_display
        ipy_display(top[['ticker','price','ti65','ext_atr','adr_pct']].reset_index(drop=True))
    except Exception:
        print(top[['ticker','price','ti65','ext_atr']].to_string(index=False))

    print(f'\n  📁 Saved: {HITS_FILE} / {RESULTS_FILE}\n')

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  STOCKBEE SCAN  |  2026-08-13 13:33
  5,645 tickers  |  8 threads
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  0%|          | 0/5645 [00:00<?]

ERROR:yfinance:$AHL: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$AKO: possibly delisted; no price data found  (period=18mo)
ERROR:yfinance:$ANG: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$ATH: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:$ETI: possibly delisted; no price data found  (period=18mo)
ERROR:yfinance:$GLOP: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"User is unable to access this feature - https://bit.ly/yahoo-finance-api-feedback"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"User is unable to access this feature - https://bit.ly/yahoo-finance-api-feedback"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"User is unable to access this feature - https://bit.ly/yahoo-finance-api-feedback"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:HTTP Error 401: {"finance":{"result":null,"error":{"code":"Unauthorized","description":"Invalid Crumb"}}}
ERROR:yfinance:$N: possibly delisted; no price data found  (period=18mo)
ERROR:yfinance:$OAK: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$PHXE: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$PRIF: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")
ERROR:yfinance:$TRTN: possibly delisted; no price data found  (period=18mo) (Yahoo error = "No data found, symbol may be delisted")

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ✅ DONE  |  25.8 min  |  686 hits
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━


================================================================================
  STOCKBEE RESULTS  |  2026-08-13 13:59
  Universe: 5,645  |  Hits: 686
================================================================================

  ▌ [SCAN 1] Extreme Sales Growth (99%+ YoY)  (50 stocks)

,ticker,price,sales_pct,eps_pct,annual_sales_m,mktcap_b,avg_vol_50k,ti65,adr_pct,ext_atr,flags
0,FDMT,11.90,21664.3,None,88.2,0.62,824.9,1.067,5.35,2.30,📈
1,CRNX,84.68,2336.3,None,42.2,8.98,4435.1,1.488,0.28,34.41,📈
2,ASTS,74.25,1952.2,None,84.9,22.29,18501.4,0.887,7.86,-0.88,
3,CUE,28.33,1250.6,None,32.7,0.12,139.0,0.992,10.11,-0.01,
4,NLY,23.22,705.6,None,3172.1,17.50,7789.6,1.046,1.60,3.25,
5,UMAC,26.61,687.3,None,31.9,1.33,4461.0,1.201,10.36,2.22,📈
6,NBIS,270.23,683.9,None,873.5,73.43,20691.1,0.973,11.09,2.02,
7,VMET,10.17,593.9,None,55.3,1.10,212.8,0.906,4.79,-1.64,
8,MU,933.76,345.7,None,90274.0,1054.58,48791.1,0.954,7.50,0.24,
9,PRE,18.72,334.5,None,113.7,0.31,197.6,0.983,6.76,0.02,
10,VRDN,22.76,278.7,None,71.1,2.58,2063.3,1.232,4.56,4.72,📈
11,AGIO,34.19,259.3,None,98.3,2.04,1179.5,0.982,5.57,0.69,
12,SNDK,1396.19,251.0,None,13184.0,206.72,13760.7,0.797,10.63,-1.38,
13,GOLD,44.49,244.0,None,23020.4,1.29,396.8,1.051,3.43,1.82,📈
14,ECO,64.31,239.4,None,706.5,2.51,461.4,1.145,3.62,4.24,📈
15,ALM,14.08,221.2,None,50.0,4.06,6420.4,0.850,8.47,-2.02,
16,URGN,49.26,199.2,None,188.7,2.40,772.8,1.322,5.43,6.26,📈
17,SM,32.11,174.6,None,5146.3,7.63,3798.8,1.010,4.44,1.21,
18,EQX,11.33,169.3,None,2546.2,13.23,14547.6,1.051,4.58,0.66,📈
19,SUN,74.78,164.5,None,39581.0,14.09,435.8,1.060,2.77,3.04,📈
20,CRDO,276.20,157.0,None,1335.1,51.51,7837.7,1.078,8.62,2.20,📈
21,PNFP,107.21,146.1,None,3305.6,16.20,1306.3,1.070,2.26,3.32,📈
22,ASND,247.54,144.3,None,865.8,16.24,680.7,1.028,2.84,0.39,
23,EXK,10.38,139.4,None,737.2,3.07,6782.8,1.132,5.07,3.00,📈
24,APLD,31.75,139.3,None,284.1,9.06,19748.3,0.813,8.70,-2.07,
25,MRP,30.00,138.0,None,730.3,4.98,1496.1,1.042,2.10,2.96,
26,WBI,30.94,128.0,None,750.9,1.45,1306.9,1.008,4.63,-0.50,
27,FBK,62.44,127.4,None,701.1,3.12,388.4,1.096,1.51,6.18,📈
28,SIMO,245.10,127.0,None,1313.6,8.31,1024.3,0.878,9.63,-1.22,
29,VNOM,41.04,126.6,None,2036.0,14.77,1791.7,0.945,2.39,-2.85,
30,SITM,679.89,126.5,None,467.9,20.44,565.5,1.010,7.15,0.24,
31,AMPX,12.27,125.9,None,108.1,1.79,6707.5,0.841,6.99,-2.38,
32,CMCO,19.04,125.3,None,1489.0,0.55,761.1,1.296,7.11,2.86,📈
33,TRT,11.63,123.6,None,58.3,0.12,569.2,0.949,7.76,-0.10,
34,SMCI,39.85,122.7,None,33700.2,25.78,58777.4,1.022,6.63,2.96,
35,DHT,19.22,122.1,None,723.0,3.10,3190.2,1.044,3.36,2.13,
36,CMBT,16.99,121.1,None,1950.7,4.93,1046.3,1.071,2.75,3.45,📈
37,STAA,24.77,119.6,None,290.4,1.23,818.0,0.874,5.47,-2.18,
38,CRWV,115.54,111.6,None,6227.4,63.70,29070.9,1.004,8.42,2.20,
39,TLN,362.77,111.2,None,3741.0,17.38,829.1,0.946,4.92,-0.43,
40,ELE,20.19,109.0,None,56.3,1.30,408.5,1.153,3.90,3.92,📈
41,COMP,12.65,109.0,None,10555.8,9.71,13756.1,1.219,4.73,3.97,📈
42,GLNG,54.20,108.7,None,408.5,5.52,1167.4,1.005,2.58,1.99,
43,GLAD,19.95,108.0,None,46.5,0.45,166.8,1.026,2.28,1.96,
44,AUGO,75.21,107.6,None,1230.7,6.31,1012.9,1.133,4.82,2.34,📈
45,ALAB,317.10,104.5,None,1201.9,55.01,5383.5,0.948,8.93,-0.39,
46,TER,406.07,103.9,None,4464.0,63.48,4389.4,1.024,7.03,1.00,
47,FPS,38.22,103.4,None,1196.0,9.94,8329.3,0.805,7.06,-2.98,
48,VIST,65.11,102.3,None,3525.1,7.22,857.0,0.960,3.74,-1.30,
49,ADAM,10.15,100.7,None,458.8,0.91,882.6,1.095,2.85,4.40,📈

  [SCAN 2] Sales Growth (39%/39% fail-closed 2Q)  →  No hits

  [SCAN 3] Growth/Turnaround (<=11B USD, IPO <10y)  →  No hits

  [SCAN 4] Earnings + Sales (39%E both Q / 20%S)  →  No hits

  ▌ [MOMENTUM] ATR Entry Zone (MA70 + 2xATR + DI)  (659 stocks)

,ticker,price,sales_pct,eps_pct,annual_sales_m,mktcap_b,avg_vol_50k,ti65,adr_pct,ext_atr,flags
0,FDMT,11.90,21664.3,None,88.2,0.62,824.9,1.067,5.35,2.30,📈
1,CRNX,84.68,2336.3,None,42.2,8.98,4435.1,1.488,0.28,34.41,📈
2,NLY,23.22,705.6,None,3172.1,17.50,7789.6,1.046,1.60,3.25,
3,UMAC,26.61,687.3,None,31.9,1.33,4461.0,1.201,10.36,2.22,📈
4,NBIS,270.23,683.9,None,873.5,73.43,20691.1,0.973,11.09,2.02,
...,...,...,...,...,...,...,...,...,...,...,...
654,VGM,10.45,NaN,None,NaN,0.57,162.0,1.013,0.84,2.30,
655,VOD,16.08,NaN,None,NaN,37.15,4295.7,1.069,1.44,2.97,📈
656,VOR,23.07,NaN,None,NaN,1.36,1251.5,1.327,6.51,3.97,📈
657,WGS,82.06,NaN,None,NaN,NaN,920.6,1.280,8.21,4.52,📈
658,WGO,32.78,NaN,None,NaN,NaN,727.7,1.077,3.29,2.39,📈

  Flags: 🔊 9M+vol+4%up  🚀 +4% BO  🔻 -4% BD  📈 TI65 bullish


  🏆 TOP 20 MOMENTUM STOCKS (ATR Entry Zone, ranked by TI65)

   ticker   price   ti65  ext_atr  adr_pct
0    DFNS   35.35  4.129     2.28    36.89
1    TRIB   11.30  3.749     7.33    11.80
2    DBGI   16.74  3.569     3.56    29.67
3    FBRX   76.81  2.063    17.00     0.24
4    TRAX   46.01  1.725     5.73     7.95
5     UTZ   14.14  1.531    19.69     0.33
6     FTK   36.82  1.497     5.12     8.03
7    CRNX   84.68  1.488    34.41     0.28
8    PAYS   12.88  1.484     8.27     5.17
9    TEAM  157.24  1.474     7.26     5.47
10   APPS   12.59  1.467     3.28     9.20
11    PAY   41.15  1.457     6.16     6.98
12    SLN   13.85  1.453     4.01     9.26
13    TXG   57.45  1.442     6.28     6.77
14   COAG   53.48  1.437     4.77     8.31
15   PLSE   44.46  1.431     5.98     7.84
16   VREX   18.52  1.430    10.21     2.99
17   FWRD   20.25  1.418     6.15     5.79
18   PAYC  209.44  1.408     6.76     4.45
19    FET   83.61  1.406     7.36     6.39

  📁 Saved: stockbee_hits.csv / stockbee_results.csv

In [ ]:
# @title 📋 Stockbee Final Summary — Comma-Separated Ticker Lists

from IPython.display import display, HTML

def sb_print_summary(df):
    scan_defs = [
        ('scan1',    'SCAN 1',   'Extreme Sales Growth',  '99%+ YoY revenue',              '#f59e0b'),
        ('scan2',    'SCAN 2',   'Sales Growth',          '39%/39% fail-closed 2Q',         '#10b981'),
        ('scan3',    'SCAN 3',   'Growth / Turnaround',   '<=11B USD mktcap + IPO <10y',    '#a78bfa'),
        ('scan4',    'SCAN 4',   'Earnings + Sales',      '39%E both Q + 20%S fail-closed', '#00e5ff'),
        ('momentum', 'MOMENTUM','ATR Entry Zone',         'MA70 + 2xATR + DI',              '#ef4444'),
    ]
    scan_cols = [s[0] for s in scan_defs if s[0] in df.columns]
    all_hits  = sorted(df[df[scan_cols].any(axis=1)]['ticker'].dropna().unique().tolist())

    print('\n' + '='*70)
    print(f'  STOCKBEE SUMMARY  |  {datetime.now().strftime("%Y-%m-%d %H:%M")}')
    print(f'  Scanned: {len(df):,}  |  Unique hits: {len(all_hits)}')
    print('='*70)

    group_tickers = {}
    for key, tag, name, criteria, _ in scan_defs:
        if key not in df.columns: continue
        tickers = (
            df[df[key]].sort_values('sales_pct', ascending=False, na_position='last')
            ['ticker'].dropna().unique().tolist()
        )
        group_tickers[key] = tickers
        print(f'\n  [{tag}] {name} — {criteria}')
        print(f'  Count   : {len(tickers)}')
        print(f'  Tickers : {", ".join(tickers) if tickers else "(none)"}')

    for flag, emoji, label in [
        ('flag_9mvol',     '🔊', '9M Vol + price up 4%+ (EP signal)'),
        ('flag_plus4_bo',  '🚀', '+4% Breakout (vol confirmed)'),
        ('flag_minus4_bd', '🔻', '-4% Breakdown (vol confirmed)'),
        ('flag_ti65',      '📈', 'TI65 Bullish'),
    ]:
        if flag not in df.columns: continue
        fl = sorted(df[df[flag] & df[scan_cols].any(axis=1)]['ticker'].dropna().unique().tolist())
        print(f'\n  {emoji} {label} ({len(fl)}) : {", ".join(fl) if fl else "(none)"}')

    print(f'\n  ALL HITS (A-Z) [{len(all_hits)}]: {", ".join(all_hits)}')
    print('='*70)

    # HTML card
    rows_html = ''
    for key, tag, name, criteria, color in scan_defs:
        tickers = group_tickers.get(key, [])
        chips = ' '.join(
            f'<span style="background:{color}22;border:1px solid {color}66;color:{color};'
            f'padding:2px 8px;border-radius:4px;font-family:monospace;font-size:13px;'
            f'margin:2px;display:inline-block">{t}</span>' for t in tickers
        ) or '<span style="color:#555">No hits</span>'
        rows_html += f'''
        <tr>
          <td style="padding:10px 14px;border-bottom:1px solid #1e293b;white-space:nowrap;vertical-align:top">
            <span style="background:{color}22;border:1px solid {color}55;color:{color};
              padding:3px 9px;border-radius:4px;font-family:monospace;font-weight:bold;font-size:12px">{tag}</span>
            <div style="color:#94a3b8;font-size:12px;margin-top:5px">{name}</div>
            <div style="color:#475569;font-size:11px">{criteria}</div>
          </td>
          <td style="padding:10px 14px;border-bottom:1px solid #1e293b;text-align:center;
            font-family:monospace;font-size:16px;color:#e2e8f0;vertical-align:top">{len(tickers)}</td>
          <td style="padding:10px 14px;border-bottom:1px solid #1e293b;vertical-align:top">{chips}</td>
        </tr>'''

    all_chips = ' '.join(
        f'<span style="background:#1e293b;border:1px solid #334155;color:#cbd5e1;'
        f'padding:2px 8px;border-radius:4px;font-family:monospace;font-size:13px;'
        f'margin:2px;display:inline-block">{t}</span>' for t in all_hits
    ) or '<span style="color:#555">No hits</span>'

    display(HTML(f'''
    <div style="background:#0f172a;border-radius:12px;padding:24px;margin-top:16px;font-family:sans-serif">
      <div style="color:#00e5ff;font-family:monospace;font-size:20px;font-weight:700">📡 STOCKBEE — FINAL SUMMARY</div>
      <div style="color:#475569;font-size:12px;margin:6px 0 20px">
        {datetime.now().strftime("%Y-%m-%d %H:%M")} &nbsp;·&nbsp; {len(df):,} tickers &nbsp;·&nbsp;
        <b style="color:#94a3b8">{len(all_hits)} unique hits</b>
      </div>
      <table style="width:100%;border-collapse:collapse;border:1px solid #1e293b;border-radius:8px;overflow:hidden">
        <thead><tr style="background:#1e293b">
          <th style="padding:10px 14px;text-align:left;color:#475569;font-size:11px;letter-spacing:.1em;text-transform:uppercase;border-bottom:1px solid #0f172a">Scan</th>
          <th style="padding:10px 14px;text-align:center;color:#475569;font-size:11px;letter-spacing:.1em;text-transform:uppercase;border-bottom:1px solid #0f172a">#</th>
          <th style="padding:10px 14px;text-align:left;color:#475569;font-size:11px;letter-spacing:.1em;text-transform:uppercase;border-bottom:1px solid #0f172a">Tickers</th>
        </tr></thead>
        <tbody style="background:#0f172a">
          {rows_html}
          <tr style="background:#1e293b">
            <td style="padding:12px 14px;vertical-align:top"><span style="color:#e2e8f0;font-family:monospace;font-weight:700">ALL HITS</span><div style="color:#475569;font-size:11px;margin-top:3px">unique · A-Z</div></td>
            <td style="padding:12px 14px;text-align:center;font-family:monospace;font-size:18px;font-weight:700;color:#00e5ff;vertical-align:top">{len(all_hits)}</td>
            <td style="padding:12px 14px;vertical-align:top">{all_chips}</td>
          </tr>
        </tbody>
      </table>
    </div>
    '''))

sb_print_summary(df)

======================================================================
  STOCKBEE SUMMARY  |  2026-08-13 13:59
  Scanned: 5,645  |  Unique hits: 686
======================================================================

  [SCAN 1] Extreme Sales Growth — 99%+ YoY revenue
  Count   : 50
  Tickers : FDMT, CRNX, ASTS, CUE, NLY, UMAC, NBIS, VMET, MU, PRE, VRDN, AGIO, SNDK, GOLD, ECO, ALM, URGN, SM, EQX, SUN, CRDO, PNFP, ASND, EXK, APLD, MRP, WBI, FBK, SIMO, VNOM, SITM, AMPX, CMCO, TRT, SMCI, DHT, CMBT, STAA, CRWV, TLN, ELE, COMP, GLNG, GLAD, AUGO, ALAB, TER, FPS, VIST, ADAM

  [SCAN 2] Sales Growth — 39%/39% fail-closed 2Q
  Count   : 0
  Tickers : (none)

  [SCAN 3] Growth / Turnaround — <=11B USD mktcap + IPO <10y
  Count   : 0
  Tickers : (none)

  [SCAN 4] Earnings + Sales — 39%E both Q + 20%S fail-closed
  Count   : 0
  Tickers : (none)

  [MOMENTUM] ATR Entry Zone — MA70 + 2xATR + DI
  Count   : 659
  Tickers : FDMT, CRNX, NLY, UMAC, NBIS, DNTH, VRDN, ECO, URGN, SLN, SUN, CRDO, PNFP, EXK, MRP, FBK, CMCO, SMCI, DHT, CMBT, CRWV, COMP, ELE, AUGO, ADAM, WAT, OTF, TIC, NIC, NVDA, AEBI, NVEC, ET, CNQ, ERO, DMLP, FENC, FTK, TARS, GPN, TXO, FRO, VSEC, CNOB, OMC, TNK, ARX, APH, PBF, SKYH, DLO, FRST, CVE, MRX, MPC, SKWD, OKE, CSW, CVX, SLF, FMNB, GKOS, VLO, TVTX, PAYS, SLDE, DK, GLP, TWFG, NBBK, AAMI, GH, OMDA, MTRN, CVBF, CLMT, ETON, EQBK, MPB, NAVN, FSM, ANET, NTRA, COP, NET, DASH, ELF, P, ADPT, AEM, NTRS, TOWN, MUFG, TBBB, GLBE, FIVE, EXPD, TAL, TEAM, CORT, FITB, KSPI, TCBX, COLB, OVV, WES, AMG, ONC, DOO, PRAA, OSBC, DGII, FIGS, PAY, ALKS, NTSK, GCT, AVBC, CXW, COF, APPS, EBC, VIA, OBK, AII, CRBG, CRWD, FTNT, PB, CPAY, SMFG, PLPC, CR, GMAB, TTAN, AJG, NOW, U, FSLY, TWST, OPRA, ASB, TOST, FMBH, AIR, SN, CXT, TWLO, OPY, AGM, ENVA, TRNS, NUE, GE, EXPO, TMDX, NWBI, DCTH, NDAQ, AES, ESQ, EVTC, APPF, DCOM, TPC, APPN, TWIN, PKE, DAL, PAR, SMTI, ADSK, SPFI, VRNS, WAY, MSFT, VIK, WAB, SYBT, NMM, PATH, ENSG, NOG, ETN, EW, STT, CWT, ABNB, ACAD, DAR, GFL, VEEV, DLR, DT, PBT, FRSH, UAL, ESTC, AVAH, UBS, ALKT, FVCB, DXPE, EXLS, FRPT, VOYG, CNK, VSXY, FFBC, SIBN, OTLY, COSO, NEM, GEO, PGY, UFPT, CTO, AME, TBPH, FA, TRU, FBNC, SMBK, PEN, FAST, PKG, ARMK, NSIT, THC, NPK, V, CTRN, FSUN, MSEX, AGYS, WEX, CLBK, UMBF, MNTN, CM, THFF, EXPE, UFCS, JCAP, BNY, DRI, ESNT, WDAY, PNC, ORI, CRM, MSI, VLY, FET, ONB, FCF, FHI, EFSC, DXCM, AMP, PHR, SLG, CRAI, ATRC, NWG, EWBC, ADBE, ALLE, CP, FFIN, PAYX, VRTX, NTAP, CNXN, FULT, ATRO, CLH, DCO, CTBI, TBI, DINO, URI, PRCH, CNO, SXT, MTUS, UNP, NSC, CVLT, WASH, AORT, CNI, TILE, ECPG, GOOD, OKTA, GABC, NEO, ULTA, NIQ, EPR, TRUP, TXRH, THRM, PCTY, NEXN, ATR, ALL, NWSA, NWS, PI, PH, ATI, CUBI, NCNO, MPLX, WAFD, TMO, SSNC, FIVN, MTW, TAK, USB, ALNT, DGX, ABBV, CSX, CON, NTNX, OII, A, WFC, TX, MSA, AMRX, KRT, TDY, MYE, PAYC, EHC, PFS, MORN, AMGN, MMSI, TRI, ALC, SYK, AIZ, CLMB, TRST, ALRM, NTB, SRCE, PACS, NBTB, FTI, APA, SMBC, CTAS, APAM, NHC, BOBS, FWRD, TENB, USPH, NDSN, FISI, ABM, ALRS, DB, USLM, CSL, UHS, CVCO, SONY, GD, NMIH, SXI, ADUS, ANGO, TCBK, CNS, COO, ABT, TREX, STVN, BNS, GIC, W, VLTO, SLP, UMH, SVV, AIT, ASH, STE, FBP, NRIM, UCB, OWL, NVST, ARDT, GFF, NEU, STRC, FRBA, ADP, FHN, TGT, UVE, OSK, CPF, CTEV, OMF, PFG, WF, FDS, GEN, MRSH, MMYT, PAG, TD, GPC, CSWC, VAC, DCI, SJM, GEHC, GNW, ARES, UBSI, TNDM, ACN, EPAC, SPSC, DHR, FNB, GL, STBA, CQP, MT, TFC, NOC, COR, MRK, TRIN, CPK, VNO, SYY, OFG, APD, CTSH, MTD, USFD, PFBC, DIN, ALOT, THG, DPZ, ACT, MTB, UNF, TRMK, GO, CNR, GEF, WBS, GGG, EAT, AFG, AUDC, FND, EMR, AMH, AUB, CNA, UFPI, PFE, GIB, MMM, DV, TSCO, NX, SOLV, AON, OPCH, MSGS, GM, SYF, BOC, ACA, NSP, ERIE, EPC, MSGE, VREX, EBF, ANF, UTZ, GCMG, SKY, PK, ENR, GIS, SSB, SW, OSPN, PD, DBX, MRBK, OZK, SWK, MSBI, OC, TRV, CNMD, TDW, UNM, NEOG, ACHC, ORRF, SLM, GPK, AOS, TEVA, APOG, DXC, CMCSA, VSAT, SON, VOYA, PEBO, EGBN, TECH, FLS, FIBK, GLIBK, CLX, KSS, VNT, OGN, DGICA, CRL, MTG, DLB, CLW, CPB, TTEK, FOXF, VRTS, TNET, ETD, CODI, NOMD, EC, AMCX, APO, AMTB, TBBK, WBD, TXG, NUTX, PESI, FEIM, AOUT, AIRO, TPG, TSAT, TSLX, ATHM, DBGI, EQH, FWONK, FWONA, EMBJ, OBDC, ARCC, NRIX, ADX, AGNC, AMLX, ANRO, AOD, APGE, APXT, ARQQ, ARXS, ARTV, ASGI, AVAV, CLYM, CMPS, COAG, CRVS, CSQ, DBRG, DEO, DFTX, DFNS, DLY, DMRA, DNLI, DRTS, DSGN, DYN, ECAT, EFR, ELVN, ERAS, ETV, EVT, EWTX, EXG, FBRX, FFC, FRA, FSK, FTH, GDV, GHRS, HZO, IEX, IDYA, JBSS, LEGH, NCI, NFJ, NPAC, NVCT, NXG, ORIC, ORKA, PCAP, PCVX, PHVS, PLSE, PRAX, PRGO, PRK, PRGS, PRI, RLI, SKE, SPTX, SPXX, SUNC, SYRE, TECX, THQ, THW, TLX, TRAX, TRIB, UL, VGM, VOD, VOR, WGS, WGO

  🔊 9M Vol + price up 4%+ (EP signal) (1) : ARX

  🚀 +4% Breakout (vol confirmed) (3) : AII, AIRO, ARX

  🔻 -4% Breakdown (vol confirmed) (0) : (none)

  📈 TI65 Bullish (577) : A, AAMI, ABBV, ABM, ABNB, ABT, ACA, ACAD, ACHC, ACN, ACT, ADAM, ADBE, ADP, ADPT, ADSK, ADUS, AEBI, AEM, AFG, AGM, AGYS, AII, AIR, AIRO, AIT, AIZ, AJG, ALC, ALKS, ALKT, ALL, ALLE, ALNT, ALOT, ALRM, ALRS, AMCX, AME, AMG, AMGN, AMLX, AMP, AMRX, AMTB, ANET, ANF, ANGO, ANRO, AORT, AOS, AOUT, APA, APAM, APGE, APH, APO, APOG, APPF, APPN, APPS, ARCC, ARDT, ARES, ARMK, ARQQ, ARTV, ARXS, ASB, ASH, ATHM, ATI, ATR, ATRC, ATRO, AUB, AUDC, AUGO, AVAH, AVAV, AVBC, BNS, BNY, BOBS, BOC, CLBK, CLMB, CLMT, CLW, CLX, CLYM, CMBT, CMCO, CMCSA, CMPS, CNA, CNK, CNMD, CNO, CNR, CNS, CNXN, COAG, CODI, COF, COMP, CON, COO, COP, COR, CORT, CPAY, CPB, CPF, CPK, CQP, CR, CRAI, CRBG, CRDO, CRL, CRM, CRNX, CRVS, CRWD, CSL, CSW, CSWC, CTAS, CTBI, CTEV, CTRN, CTSH, CUBI, CVBF, CVCO, CVLT, CWT, CXT, CXW, DAL, DASH, DB, DBGI, DBX, DCI, DCO, DCTH, DEO, DFNS, DFTX, DGICA, DGII, DGX, DHR, DIN, DINO, DK, DLB, DLO, DMRA, DNLI, DNTH, DOO, DPZ, DRI, DRTS, DSGN, DT, DV, DXC, DXCM, DXPE, DYN, EAT, EBC, EBF, EC, ECO, ECPG, EHC, ELE, ELF, ELVN, EMBJ, EMR, ENR, ENSG, ENVA, EPAC, EPC, EQBK, EQH, EQX, ERAS, ERIE, ERO, ESNT, ESQ, ESTC, ET, ETD, ETN, ETON, EVT, EVTC, EWTX, EXK, EXLS, EXPD, EXPE, EXPO, FA, FAST, FBK, FBNC, FBP, FBRX, FCF, FDMT, FDS, FEIM, FENC, FET, FHI, FIGS, FISI, FITB, FIVE, FIVN, FLS, FMBH, FMNB, FND, FOXF, FRBA, FRO, FRPT, FRSH, FRST, FSK, FSLY, FSM, FSUN, FTH, FTK, FTNT, FULT, FVCB, FWONA, FWONK, FWRD, GABC, GCMG, GCT, GD, GE, GEF, GEHC, GEN, GEO, GFF, GFL, GGG, GH, GHRS, GIB, GIC, GIS, GKOS, GL, GLBE, GLIBK, GM, GMAB, GO, GOLD, GPC, GPK, GPN, HZO, IDYA, IEX, JCAP, KRT, KSPI, KSS, LEGH, MMM, MMSI, MMYT, MNTN, MORN, MPB, MPC, MPLX, MRK, MRSH, MRX, MSA, MSBI, MSEX, MSFT, MSGE, MSI, MT, MTB, MTD, MTG, MTRN, MTUS, MTW, MUFG, MYE, NAVN, NBBK, NBTB, NCI, NCNO, NDAQ, NDSN, NEM, NEO, NEOG, NET, NEU, NEXN, NHC, NIC, NIQ, NMIH, NMM, NOC, NOG, NOMD, NOW, NPK, NRIX, NSC, NSIT, NSP, NTAP, NTB, NTNX, NTRA, NTRS, NTSK, NUE, NUTX, NVCT, NVDA, NVEC, NVST, NWBI, NWG, NWS, NWSA, NX, OBDC, OBK, OC, OFG, OII, OKTA, OMC, OMDA, OMF, ONB, ONC, OPCH, OPRA, OPY, ORI, ORIC, ORKA, ORRF, OSBC, OSK, OSPN, OTF, OTLY, OVV, OWL, P, PACS, PAG, PAR, PATH, PAY, PAYC, PAYS, PAYX, PBF, PBT, PCTY, PCVX, PD, PEBO, PESI, PFBC, PFE, PFS, PGY, PH, PHR, PHVS, PI, PK, PKE, PKG, PLPC, PLSE, PNC, PNFP, PRAA, PRAX, PRCH, PRGO, PRGS, PRI, PRK, RLI, SIBN, SJM, SKE, SKWD, SKY, SKYH, SLDE, SLF, SLG, SLM, SLN, SLP, SMBC, SMBK, SMFG, SMTI, SN, SOLV, SON, SONY, SPFI, SPSC, SPTX, SRCE, SSB, SSNC, STBA, STE, STRC, STT, STVN, SUN, SUNC, SVV, SW, SWK, SXI, SXT, SYBT, SYF, SYK, SYRE, SYY, TAK, TAL, TARS, TBBB, TBBK, TBI, TCBK, TCBX, TDW, TDY, TEAM, TECH, TECX, TENB, TEVA, TGT, THC, THFF, THG, THRM, THW, TIC, TILE, TLX, TMDX, TMO, TNDM, TNET, TNK, TOST, TOWN, TPC, TPG, TRAX, TREX, TRI, TRIB, TRIN, TRNS, TRU, TRUP, TRV, TSAT, TSCO, TSLX, TTAN, TTEK, TVTX, TWFG, TWIN, TWLO, TWST, TX, TXG, TXO, TXRH, U, UAL, UBS, UBSI, UFCS, UFPI, UFPT, UHS, UL, ULTA, UMAC, UMBF, UNF, UNP, URGN, URI, USB, USFD, USLM, USPH, UTZ, UVE, V, VAC, VEEV, VIA, VIK, VLO, VLTO, VNO, VNT, VOD, VOR, VOYA, VOYG, VRDN, VREX, VRNS, VRTS, VRTX, VSAT, VSEC, VSXY, W, WAB, WASH, WAT, WAY, WBS, WDAY, WES, WEX, WF, WFC, WGO, WGS

  ALL HITS (A-Z) [686]: A, AAMI, ABBV, ABM, ABNB, ABT, ACA, ACAD, ACHC, ACN, ACT, ADAM, ADBE, ADP, ADPT, ADSK, ADUS, ADX, AEBI, AEM, AES, AFG, AGIO, AGM, AGNC, AGYS, AII, AIR, AIRO, AIT, AIZ, AJG, ALAB, ALC, ALKS, ALKT, ALL, ALLE, ALM, ALNT, ALOT, ALRM, ALRS, AMCX, AME, AMG, AMGN, AMH, AMLX, AMP, AMPX, AMRX, AMTB, ANET, ANF, ANGO, ANRO, AOD, AON, AORT, AOS, AOUT, APA, APAM, APD, APGE, APH, APLD, APO, APOG, APPF, APPN, APPS, APXT, ARCC, ARDT, ARES, ARMK, ARQQ, ARTV, ARX, ARXS, ASB, ASGI, ASH, ASND, ASTS, ATHM, ATI, ATR, ATRC, ATRO, AUB, AUDC, AUGO, AVAH, AVAV, AVBC, BNS, BNY, BOBS, BOC, CLBK, CLH, CLMB, CLMT, CLW, CLX, CLYM, CM, CMBT, CMCO, CMCSA, CMPS, CNA, CNI, CNK, CNMD, CNO, CNOB, CNQ, CNR, CNS, CNXN, COAG, CODI, COF, COLB, COMP, CON, COO, COP, COR, CORT, COSO, CP, CPAY, CPB, CPF, CPK, CQP, CR, CRAI, CRBG, CRDO, CRL, CRM, CRNX, CRVS, CRWD, CRWV, CSL, CSQ, CSW, CSWC, CSX, CTAS, CTBI, CTEV, CTO, CTRN, CTSH, CUBI, CUE, CVBF, CVCO, CVE, CVLT, CVX, CWT, CXT, CXW, DAL, DAR, DASH, DB, DBGI, DBRG, DBX, DCI, DCO, DCOM, DCTH, DEO, DFNS, DFTX, DGICA, DGII, DGX, DHR, DHT, DIN, DINO, DK, DLB, DLO, DLR, DLY, DMLP, DMRA, DNLI, DNTH, DOO, DPZ, DRI, DRTS, DSGN, DT, DV, DXC, DXCM, DXPE, DYN, EAT, EBC, EBF, EC, ECAT, ECO, ECPG, EFR, EFSC, EGBN, EHC, ELE, ELF, ELVN, EMBJ, EMR, ENR, ENSG, ENVA, EPAC, EPC, EPR, EQBK, EQH, EQX, ERAS, ERIE, ERO, ESNT, ESQ, ESTC, ET, ETD, ETN, ETON, ETV, EVT, EVTC, EW, EWBC, EWTX, EXG, EXK, EXLS, EXPD, EXPE, EXPO, FA, FAST, FBK, FBNC, FBP, FBRX, FCF, FDMT, FDS, FEIM, FENC, FET, FFBC, FFC, FFIN, FHI, FHN, FIBK, FIGS, FISI, FITB, FIVE, FIVN, FLS, FMBH, FMNB, FNB, FND, FOXF, FPS, FRA, FRBA, FRO, FRPT, FRSH, FRST, FSK, FSLY, FSM, FSUN, FTH, FTI, FTK, FTNT, FULT, FVCB, FWONA, FWONK, FWRD, GABC, GCMG, GCT, GD, GDV, GE, GEF, GEHC, GEN, GEO, GFF, GFL, GGG, GH, GHRS, GIB, GIC, GIS, GKOS, GL, GLAD, GLBE, GLIBK, GLNG, GLP, GM, GMAB, GNW, GO, GOLD, GOOD, GPC, GPK, GPN, HZO, IDYA, IEX, JBSS, JCAP, KRT, KSPI, KSS, LEGH, MMM, MMSI, MMYT, MNTN, MORN, MPB, MPC, MPLX, MRBK, MRK, MRP, MRSH, MRX, MSA, MSBI, MSEX, MSFT, MSGE, MSGS, MSI, MT, MTB, MTD, MTG, MTRN, MTUS, MTW, MU, MUFG, MYE, NAVN, NBBK, NBIS, NBTB, NCI, NCNO, NDAQ, NDSN, NEM, NEO, NEOG, NET, NEU, NEXN, NFJ, NHC, NIC, NIQ, NLY, NMIH, NMM, NOC, NOG, NOMD, NOW, NPAC, NPK, NRIM, NRIX, NSC, NSIT, NSP, NTAP, NTB, NTNX, NTRA, NTRS, NTSK, NUE, NUTX, NVCT, NVDA, NVEC, NVST, NWBI, NWG, NWS, NWSA, NX, NXG, OBDC, OBK, OC, OFG, OGN, OII, OKE, OKTA, OMC, OMDA, OMF, ONB, ONC, OPCH, OPRA, OPY, ORI, ORIC, ORKA, ORRF, OSBC, OSK, OSPN, OTF, OTLY, OVV, OWL, OZK, P, PACS, PAG, PAR, PATH, PAY, PAYC, PAYS, PAYX, PB, PBF, PBT, PCAP, PCTY, PCVX, PD, PEBO, PEN, PESI, PFBC, PFE, PFG, PFS, PGY, PH, PHR, PHVS, PI, PK, PKE, PKG, PLPC, PLSE, PNC, PNFP, PRAA, PRAX, PRCH, PRE, PRGO, PRGS, PRI, PRK, RLI, SIBN, SIMO, SITM, SJM, SKE, SKWD, SKY, SKYH, SLDE, SLF, SLG, SLM, SLN, SLP, SM, SMBC, SMBK, SMCI, SMFG, SMTI, SN, SNDK, SOLV, SON, SONY, SPFI, SPSC, SPTX, SPXX, SRCE, SSB, SSNC, STAA, STBA, STE, STRC, STT, STVN, SUN, SUNC, SVV, SW, SWK, SXI, SXT, SYBT, SYF, SYK, SYRE, SYY, TAK, TAL, TARS, TBBB, TBBK, TBI, TBPH, TCBK, TCBX, TD, TDW, TDY, TEAM, TECH, TECX, TENB, TER, TEVA, TFC, TGT, THC, THFF, THG, THQ, THRM, THW, TIC, TILE, TLN, TLX, TMDX, TMO, TNDM, TNET, TNK, TOST, TOWN, TPC, TPG, TRAX, TREX, TRI, TRIB, TRIN, TRMK, TRNS, TRST, TRT, TRU, TRUP, TRV, TSAT, TSCO, TSLX, TTAN, TTEK, TVTX, TWFG, TWIN, TWLO, TWST, TX, TXG, TXO, TXRH, U, UAL, UBS, UBSI, UCB, UFCS, UFPI, UFPT, UHS, UL, ULTA, UMAC, UMBF, UMH, UNF, UNM, UNP, URGN, URI, USB, USFD, USLM, USPH, UTZ, UVE, V, VAC, VEEV, VGM, VIA, VIK, VIST, VLO, VLTO, VLY, VMET, VNO, VNOM, VNT, VOD, VOR, VOYA, VOYG, VRDN, VREX, VRNS, VRTS, VRTX, VSAT, VSEC, VSXY, W, WAB, WAFD, WASH, WAT, WAY, WBD, WBI, WBS, WDAY, WES, WEX, WF, WFC, WGO, WGS
======================================================================

## Publish Results — JSON / Excel / Supabase

In [ ]:
# ============================================================
# PUBLISH RESULTS — JSON + EXCEL + SUPABASE
# Google Drive / Google Sheets publishing is intentionally disabled.
# ============================================================
import os
from pathlib import Path
import pandas as pd
OUTDIR=Path("public/data"); OUTDIR.mkdir(parents=True,exist_ok=True)
from scripts.supabase_scan_writer import upload_scan_records, cleanup_scan_history

# Stockbee files
if "df" not in globals() or not isinstance(df,pd.DataFrame):
    raise RuntimeError("Stockbee result DataFrame 'df' was not found.")
stockbee_df=df.copy()
stockbee_df.to_json(OUTDIR/"stockbee.json",orient="records",indent=2,date_format="iso")
stockbee_df.to_excel(OUTDIR/"stockbee.xlsx",index=False)
print(f"✅ Stockbee JSON: {OUTDIR/'stockbee.json'}")
print(f"✅ Stockbee Excel: {OUTDIR/'stockbee.xlsx'}")

# Stockbee Supabase rows
ticker_col=next((x for x in ["ticker","Ticker","symbol","Symbol"] if x in stockbee_df.columns),None)
if ticker_col is None:
    raise RuntimeError(f"Stockbee ticker column not found: {list(stockbee_df.columns)}")
STOCKBEE_SCANS={"scan1":"Stockbee Extreme Sales","scan2":"Stockbee Sales Growth","scan3":"Stockbee Growth Turnaround","scan4":"Stockbee Earnings Sales","momentum":"Stockbee ATR Momentum"}
stockbee_rows=[]
for col,label in STOCKBEE_SCANS.items():
    if col not in stockbee_df.columns:
        print(f"⚠️ {col} not present — skipping")
        continue
    for _,row in stockbee_df[stockbee_df[col].fillna(False).astype(bool)].iterrows():
        ticker=str(row[ticker_col]).strip()
        if ticker and ticker.lower()!="nan":
            stockbee_rows.append({"scan_name":label,"ticker":ticker,"universe":"S&P 500"})

# Daily scanner Supabase rows
daily_rows=[]
if "_daily_df" in globals() and isinstance(_daily_df,pd.DataFrame):
    for _,row in _daily_df.iterrows():
        ticker=str(row.get("Ticker","")).strip()
        scan=str(row.get("Scan","")).strip()
        universe=str(row.get("Universe","USA")).strip()
        if ticker and ticker.lower()!="nan" and scan and scan.lower()!="nan":
            daily_rows.append({"scan_name":scan,"ticker":ticker,"universe":universe})

print(f"📊 Stockbee rows: {len(stockbee_rows)}")
print(f"📊 Daily rows: {len(daily_rows)}")

stockbee_uploaded=upload_scan_records(stockbee_rows,market="usa",timeframe="daily",run_id=os.environ.get("GITHUB_RUN_ID")) if stockbee_rows else 0
daily_uploaded=upload_scan_records(daily_rows,market="usa",timeframe="eod",run_id=os.environ.get("GITHUB_RUN_ID")) if daily_rows else 0
print(f"✅ Stockbee uploaded: {stockbee_uploaded}")
print(f"✅ Daily uploaded: {daily_uploaded}")

cleanup_scan_history(30)
print("✅ Supabase 30-day history cleanup completed")

## 💾 Supabase Config

In [ ]:

# ── SUPABASE CONFIG ───────────────────────────────────────────────────
# Set these once — get values from app.supabase.com → Settings → API
SUPABASE_URL = "https://bcstlymgngynzktjgofj.supabase.co"   # e.g. https://abcdefgh.supabase.co
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjc3RseW1nbmd5bnprdGpnb2ZqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NjM2MTI3NiwiZXhwIjoyMTAxOTM3Mjc2fQ.02FdqyqpIPJ9NMj1Zhc1xTMRdrXe8B1h2nweQuY9hOY"                       # Settings → API → anon public key

import os
SUPABASE_URL = os.environ.get("SUPABASE_URL", SUPABASE_URL)
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", SUPABASE_KEY)

print(f"Supabase URL : {SUPABASE_URL[:30]}...")
print(f"Supabase Key : {SUPABASE_KEY[:20]}...")

In [ ]:

# ── SUPABASE INSERT HELPER ────────────────────────────────────────────
import requests as _req, json as _json
from datetime import datetime as _dt

def db_insert(rows: list, scan_type: str, market: str):
    """
    Insert scan results into Supabase.
    rows: list of dicts with keys: scan_name, ticker, universe,
          close_price (opt), volume (opt), change_pct (opt)
    """
    if not rows:
        print(f"  db_insert: no rows for {scan_type}/{market}")
        return

    today = _dt.now().strftime('%Y-%m-%d')
    now   = _dt.now().isoformat()

    # First delete today's rows for this scan_type + market (avoid duplicates on re-run)
    del_resp = _req.delete(
        f"{SUPABASE_URL}/rest/v1/scan_results",
        headers={
            "apikey":        SUPABASE_KEY,
            "Authorization": f"Bearer {SUPABASE_KEY}",
            "Content-Type":  "application/json",
        },
        params={
            "scan_date": f"eq.{today}",
            "scan_type": f"eq.{scan_type}",
            "market":    f"eq.{market}",
        }
    )
    if del_resp.status_code not in (200, 204):
        print(f"  ⚠ Delete existing rows: {del_resp.status_code} {del_resp.text[:80]}")

    # Build insert payload
    payload = []
    for r in rows:
        payload.append({
            "scan_date":   today,
            "scan_time":   now,
            "scan_type":   scan_type,
            "market":      market,
            "universe":    r.get("universe", ""),
            "scan_name":   r.get("scan_name", ""),
            "ticker":      r.get("ticker", ""),
            "close_price": r.get("close_price"),
            "volume":      r.get("volume"),
            "change_pct":  r.get("change_pct"),
            "avg_vol_20":  r.get("avg_vol_20"),
        })

    # Insert in batches of 500
    batch_size = 500
    total_inserted = 0
    for i in range(0, len(payload), batch_size):
        batch = payload[i:i+batch_size]
        resp = _req.post(
            f"{SUPABASE_URL}/rest/v1/scan_results",
            headers={
                "apikey":        SUPABASE_KEY,
                "Authorization": f"Bearer {SUPABASE_KEY}",
                "Content-Type":  "application/json",
                "Prefer":        "return=minimal",
            },
            data=_json.dumps(batch)
        )
        if resp.status_code in (200, 201):
            total_inserted += len(batch)
        else:
            print(f"  ❌ Insert batch {i//batch_size+1} failed: {resp.status_code} {resp.text[:100]}")

    print(f"  ✅ Inserted {total_inserted} rows → Supabase [{scan_type}/{market}]")
    return total_inserted

In [ ]:

# ── DAILY: Insert results into Supabase ──────────────────────────────
import os
_market = os.environ.get("SCAN_MARKET", "both").upper()

_lmap = {
    'bearish_momentum':'Bearish Momentum','vcp_setup':'VCP Setup',
    'satish_bullish':'Satish Bullish','hardik':'Hardik Scan',
    'nr6':'NR6 Narrowest Range','rocket_base':'Rocket Base',
    'ep_breakout':'EP Breakout','high_20d':'20-Day High (US)',
    'high_2month':'2-Month High (US)','gapup_3pct':'Gap Up 3pct',
    'up_4pct':'Up 4pct Today',
    # New scans
    'weekly_rsi_reversal':'Weekly RSI Reversal','btst_strong':'BTST Strong',
    'btst_supertrend':'BTST Supertrend','trend_reversal':'Trend Reversal',
    'weekly_reversal':'Weekly Reversal Engulfing',
}

all_rows = []
for _k in DAILY_SCAN_KEYS:
    _lbl = _lmap.get(_k, _k)
    for _t in sp500_hits.get(_k,  []): all_rows.append({"scan_name":_lbl,"ticker":_t,"universe":"S&P 500"})
    for _t in r2000_hits.get(_k,  []): all_rows.append({"scan_name":_lbl,"ticker":_t,"universe":"Russell 2000"})
    for _t in nifty_hits.get(_k,  []): all_rows.append({"scan_name":_lbl,"ticker":_t,"universe":"Nifty 500"})

db_insert(all_rows, scan_type="Daily", market=_market)
print(f"Daily: {len(all_rows)} rows inserted")